### ISSUE TITLE
Already disposed error

### ISSUE THREAD

**Issue by zjhmale** [rikvdkleij/intellij-haskell#112]
This error will be triggered when you close a Haskell project as the `stack repl` is still under processing.

The full error stack message is here.

>java.lang.AssertionError: Already disposed: Project (Disposed) idris-lsp
com.google.common.util.concurrent.ExecutionError: java.lang.AssertionError: Already disposed: Project (Disposed) idris-lsp
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2212)
	at com.google.common.cache.LocalCache.get(LocalCache.java:4053)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4057)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4986)
	at intellij.haskell.external.component.BrowseModuleComponent$.findImportedModuleIdentifiers(BrowseModuleComponent.scala:85)
	at intellij.haskell.external.component.HaskellComponentsManager$.$anonfun$preloadAllLibraryModuleIdentifiers$5(HaskellComponentsManager.scala:117)
	at scala.collection.immutable.List.foreach(List.scala:378)
	at scala.collection.generic.TraversableForwarder.foreach(TraversableForwarder.scala:35)
	at scala.collection.generic.TraversableForwarder.foreach$(TraversableForwarder.scala:35)
	at scala.collection.mutable.ListBuffer.foreach(ListBuffer.scala:44)
	at intellij.haskell.external.component.HaskellComponentsManager$.preloadAllLibraryModuleIdentifiers(HaskellComponentsManager.scala:114)
	at intellij.haskell.external.component.HaskellComponentsManager$.preloadModuleIdentifiersCaches(HaskellComponentsManager.scala:88)
	at intellij.haskell.external.component.StackProjectStartupManager$$anon$1$$anon$2.run(StackProjectStartupManager.scala:50)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:309)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.AssertionError: Already disposed: Project (Disposed) idris-lsp
	at com.intellij.openapi.components.impl.ComponentManagerImpl.getComponent(ComponentManagerImpl.java:172)
	at intellij.haskell.external.repl.StackReplsManager$.getGlobalRepl(StackReplsManager.scala:33)
	at intellij.haskell.external.component.BrowseModuleComponent$$anon$1.$anonfun$findModuleIdentifiers$1(BrowseModuleComponent.scala:58)
	at scala.Option.flatMap(Option.scala:171)
	at intellij.haskell.external.component.BrowseModuleComponent$$anon$1.findModuleIdentifiers(BrowseModuleComponent.scala:56)
	at intellij.haskell.external.component.BrowseModuleComponent$$anon$1.load(BrowseModuleComponent.scala:42)
	at intellij.haskell.external.component.BrowseModuleComponent$$anon$1.load(BrowseModuleComponent.scala:39)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3628)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2336)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2295)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2208)
	... 18 more

**Comment by rikvdkleij** [comment]
Pushed fix.

**Comment by zjhmale** [comment]
@rikvdkleij Cool! But I think this error is still standing there, you can close a loading project and then reopen it and then close it quickly before the `stack repl` process finished and then reopened it for times to reproduce this error.

Oh and this time the error log is changed

>Already disposed: Project (Disposed) idris-lsp
java.lang.AssertionError: Already disposed: Project (Disposed) idris-lsp
	at com.intellij.openapi.components.impl.ComponentManagerImpl.getComponent(ComponentManagerImpl.java:172)
	at com.intellij.openapi.roots.ProjectRootManager.getInstance(ProjectRootManager.java:42)
	at intellij.haskell.sdk.HaskellSdkType$.getStackPath(HaskellSdkType.scala:111)
	at intellij.haskell.external.repl.StackReplProcess.start(StackReplProcess.scala:134)
	at intellij.haskell.external.repl.StackReplProcess.restart(StackReplProcess.scala:236)
	at intellij.haskell.external.component.StackProjectStartupManager$$anon$1$$anon$2.run(StackProjectStartupManager.scala:56)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:309)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
java.lang.AssertionError: Already disposed: Project (Disposed) idris-lsp
	at com.intellij.openapi.components.impl.ComponentManagerImpl.getComponent(ComponentManagerImpl.java:172)
	at com.intellij.openapi.roots.ProjectRootManager.getInstance(ProjectRootManager.java:42)
	at com.intellij.psi.search.GlobalSearchScopesCore$ProductionScopeFilter.<init>(GlobalSearchScopesCore.java:134)
	at com.intellij.psi.search.GlobalSearchScopesCore$ProductionScopeFilter.<init>(GlobalSearchScopesCore.java:129)
	at com.intellij.psi.search.GlobalSearchScopesCore.projectProductionScope(GlobalSearchScopesCore.java:43)
	at intellij.haskell.util.index.HaskellFileIndex$.findProjectProductionFiles(HaskellFileIndex.scala:96)
	at intellij.haskell.util.index.HaskellFileIndex$.findProjectProductionPsiFiles(HaskellFileIndex.scala:92)
	at intellij.haskell.external.component.HaskellComponentsManager$.$anonfun$preloadAllLibraryModuleIdentifiers$1(HaskellComponentsManager.scala:109)
	at com.intellij.openapi.application.TransactionGuardImpl$6.run(TransactionGuardImpl.java:318)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:417)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:401)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:843)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:679)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:391)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

![screenshot](https://cloud.githubusercontent.com/assets/6234553/21686206/8803619e-d39f-11e6-9e5d-65085af81199.gif)

**Comment by rikvdkleij** [comment]
You are searching for corner cases :smile: This is a different place.

**Comment by zjhmale** [comment]
Yes, this is a different place against the initial problem indeed 😄 
>You are searching for corner cases 😄 This is a different place.

**Comment by rikvdkleij** [comment]
Pushed another fix.

**Comment by zjhmale** [comment]
Great! Thanks 😄
