### ISSUE TITLE
"No Cabal file info" error while creating new Haskell project or module

### ISSUE THREAD

**Issue by melentye** [rikvdkleij/intellij-haskell#208]
Hello! I get a "No Cabal file info. Could not create Haskell module because could not retrieve or parse Cabal file for package path None" when trying to create a new Haskell project or module using the plugin.

macOS 10.12.6, IntelliJ CE 2017.2.2, IntelliJ-Haskell 1.0.0-beta11
Haskell Platform 8.0.2 installed via homebrew

Stacktrace from IntelliJ:

```
null
java.lang.NullPointerException
	at intellij.haskell.external.repl.StackReplsManager$.$anonfun$getProjectRepl$1(StackReplsManager.scala:44)
	at scala.Option.flatMap(Option.scala:171)
	at intellij.haskell.external.repl.StackReplsManager$.getProjectRepl(StackReplsManager.scala:44)
	at intellij.haskell.external.component.LoadComponent$.load(LoadComponent.scala:75)
	at intellij.haskell.external.component.HaskellComponentsManager$.loadHaskellFile(HaskellComponentsManager.scala:93)
	at intellij.haskell.annotator.HaskellAnnotator.doAnnotate(HaskellAnnotator.scala:66)
	at intellij.haskell.annotator.HaskellAnnotator.doAnnotate(HaskellAnnotator.scala:42)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass.doAnnotate(ExternalToolPass.java:211)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass.access$500(ExternalToolPass.java:47)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass$1.run(ExternalToolPass.java:158)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:337)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:327)
	at com.intellij.util.ui.update.MergingUpdateQueue.lambda$flush$1(MergingUpdateQueue.java:277)
	at com.intellij.util.ui.update.MergingUpdateQueue.flush(MergingUpdateQueue.java:291)
	at com.intellij.util.ui.update.MergingUpdateQueue.run(MergingUpdateQueue.java:246)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:246)
	at com.intellij.util.Alarm$Request.runSafely(Alarm.java:417)
	at com.intellij.util.Alarm$Request.access$700(Alarm.java:344)
	at com.intellij.util.Alarm$Request$1.run(Alarm.java:384)
	at com.intellij.util.Alarm$Request.run(Alarm.java:395)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:237)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:212)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

How can I help debug?

**Comment by rikvdkleij** [comment]
Looks like content of your `stack.yaml` file is not according to what plugin expects. It can not find a path to directory which contains Cabal file.

Do you have example project?

**Comment by melentye** [comment]
The issue occurs when creating a _new_ module or project so there was no preexisting stack.yaml in the project. Here's the directory listing from the created project:
```
ls -1 haskelltest/
LICENSE
README.md
Setup.hs
app
haskelltest.cabal
src
test
```

I also seem to get  "AWT events are not allowed inside write action: sun.awt.PeerEvent[INVOCATION_DEFAULT,runnable=sun.awt.SunToolkit$1@1bfd9f64,notifier=null,catchExceptions=false,when=1503334860590] on sun.lwawt.macosx.LWCToolkit@291782ff" with stacktrace

```
AWT events are not allowed inside write action: sun.awt.PeerEvent[INVOCATION_DEFAULT,runnable=sun.awt.SunToolkit$1@1bfd9f64,notifier=null,catchExceptions=false,when=1503334860590] on sun.lwawt.macosx.LWCToolkit@291782ff
java.lang.Throwable
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:132)
	at com.intellij.openapi.application.impl.NoSwingUnderWriteAction.lambda$watchForEvents$0(NoSwingUnderWriteAction.java:36)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:376)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:109)
	at java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:190)
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:235)
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:233)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:233)
	at java.awt.Dialog.show(Dialog.java:1084)
	at java.awt.Component.show(Component.java:1679)
	at java.awt.Component.setVisible(Component.java:1631)
	at java.awt.Window.setVisible(Window.java:1014)
	at java.awt.Dialog.setVisible(Dialog.java:1005)
	at com.intellij.ui.messages.SheetMessage.<init>(SheetMessage.java:169)
	at com.intellij.ui.messages.JBMacMessages.showErrorDialog(JBMacMessages.java:202)
	at com.intellij.openapi.ui.Messages.showErrorDialog(Messages.java:730)
	at intellij.haskell.module.HaskellModuleBuilder.setupRootModel(HaskellModuleBuilder.scala:78)
	at com.intellij.ide.util.projectWizard.ModuleBuilder.setupModule(ModuleBuilder.java:263)
	at intellij.haskell.module.HaskellModuleBuilder.setupModule(HaskellModuleBuilder.scala:115)
	at com.intellij.ide.util.projectWizard.ModuleBuilder.createModule(ModuleBuilder.java:256)
	at com.intellij.ide.util.projectWizard.ModuleBuilder.createAndCommitIfNeeded(ModuleBuilder.java:294)
	at com.intellij.ide.util.projectWizard.ModuleBuilder.lambda$commitModule$3(ModuleBuilder.java:337)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:1055)
	at com.intellij.ide.util.projectWizard.ModuleBuilder.commitModule(ModuleBuilder.java:336)
	at com.intellij.openapi.roots.ui.configuration.actions.NewModuleAction.createModuleFromWizard(NewModuleAction.java:82)
	at com.intellij.openapi.roots.ui.configuration.actions.NewModuleAction.actionPerformed(NewModuleAction.java:61)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:216)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:233)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.lambda$actionPerformed$0(ActionMenuItem.java:310)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.runOnOwnContext(FocusManagerImpl.java:911)
	at com.intellij.openapi.wm.impl.IdeFocusManagerImpl.runOnOwnContext(IdeFocusManagerImpl.java:136)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.actionPerformed(ActionMenuItem.java:300)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.lambda$fireActionPerformed$0(ActionMenuItem.java:117)
	at com.intellij.openapi.application.TransactionGuardImpl.runSyncTransaction(TransactionGuardImpl.java:86)
	at com.intellij.openapi.application.TransactionGuardImpl.lambda$submitTransaction$1(TransactionGuardImpl.java:109)
	at com.intellij.openapi.application.TransactionGuardImpl.submitTransaction(TransactionGuardImpl.java:118)
	at com.intellij.openapi.application.TransactionGuard.submitTransaction(TransactionGuard.java:122)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.fireActionPerformed(ActionMenuItem.java:117)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.JToggleButton$ToggleButtonModel.setPressed(JToggleButton.java:308)
	at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
	at com.apple.laf.ScreenMenuItemCheckbox.itemStateChanged(ScreenMenuItemCheckbox.java:193)
	at java.awt.CheckboxMenuItem.processItemEvent(CheckboxMenuItem.java:389)
	at java.awt.CheckboxMenuItem.processEvent(CheckboxMenuItem.java:357)
	at java.awt.MenuComponent.dispatchEventImpl(MenuComponent.java:355)
	at java.awt.MenuComponent.dispatchEvent(MenuComponent.java:343)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:767)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:737)
	at java.awt.EventQueue$4.run(EventQueue.java:735)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:821)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:649)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:365)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by rikvdkleij** [comment]
Only Stack projects are supported. So there must be a `stack.yaml`.

How did you create this project directory?

**Comment by melentye** [comment]
I am using "File - New - Project... - Haskell Module" to create a project thinking that it'd spin it up from scratch. Is having an existing project with stack.yaml a prerequisite?

**Comment by rikvdkleij** [comment]
Yes, that should work. I can not reproduce your issue.

Do you select `Haskell Tool Stack` as Project SDK?

**Comment by melentye** [comment]
I do

**Comment by rikvdkleij** [comment]
> Haskell Platform 8.0.2 installed via homebrew

Did you also installed Stack? Normally you have to otherwise you could not create Haskell Tool Stack SDK.

Enable Haskell Event Log to get information of what is going wrong.

**Comment by melentye** [comment]
Stack 1.3.2 is installed with the Haskell Platform - that's the one IntelliJ found automatically as the SDK. I tried running `stack upgrade` which installed version 1.5.1 into `~/.local/` - having that set up in IntelliJ yields the same results.

Can you point me to how exactly would I enable the event log please?

**Comment by rikvdkleij** [comment]
Settings -> Appearance & Behavior -> Notifications.

It looks like a Stack initialization problem.  You can also try to use `stack new` to create new project from the command line.

**Comment by melentye** [comment]
Indeed it was a problem with my Stack configuration: I was missing the template params in the `~/.stack/config.yaml`.

Thank you for helping me identify the issue. Do you think the IntelliJ-Haskell plugin could do with a more user friendly error message for such a case? Otherwise feel free to reject the ticket.

**Comment by rikvdkleij** [comment]
I'm glad you found the cause.

> Do you think the IntelliJ-Haskell plugin could do with a more user friendly error message for such a case?

I will try.

**Comment by aleqsio** [comment]
Hello,
Also experiencing this issue.
Downloaded stack, enabled this plugin, when trying to create a haskell module i get the same error:
"No Cabal file info. Could not create Haskell module because could not retrieve or parse Cabal file for package path None"

Here is my config.yaml:

```
templates:
  params:
    author-name : Aleksander
    author-email : mikucki@gmail.com
    copyright : GPL
    github-username : aleqsio
    category: My new project

```
Here is the output from stack new:

```
C:\Users\User\AppData\Roaming\local\bin>stack new test
Downloading template "new-template" to create project "test" in test\ ...
Looking for .cabal or package.yaml files to use to init the project.
Using cabal packages:
- test\test.cabal

Selecting the best among 11 snapshots...

Selected mirror https://s3.amazonaws.com/hackage.fpcomplete.com/
Downloading timestamp
Downloading snapshot
Downloading mirrors
Cannot update index (no local copy)
Downloading index
Updated package list downloaded
Populated index cache.
* Matches lts-9.6

Selected resolver: lts-9.6
Initialising configuration using resolver: lts-9.6
Total number of user packages considered: 1
Writing configuration to file: test\stack.yaml
All done.
```

Let me know if i can help with any other info.

**Comment by rikvdkleij** [comment]
@aleqsio Does your `stack.yaml` contains a package key?

**Comment by aleqsio** [comment]
Nope, it doesn't.
Here is a stack.yaml genreated with stack new
```
# This file was automatically generated by 'stack init'
#
# Some commonly used options have been documented as comments in this file.
# For advanced use and comprehensive documentation of the format, please see:
# https://docs.haskellstack.org/en/stable/yaml_configuration/

# Resolver to choose a 'specific' stackage snapshot or a compiler version.
# A snapshot resolver dictates the compiler version and the set of packages
# to be used for project dependencies. For example:
#
# resolver: lts-3.5
# resolver: nightly-2015-09-21
# resolver: ghc-7.10.2
# resolver: ghcjs-0.1.0_ghc-7.10.2
# resolver:
#  name: custom-snapshot
#  location: "./custom-snapshot.yaml"
resolver: lts-9.8

# User packages to be built.
# Various formats can be used as shown in the example below.
#
# packages:
# - some-directory
# - https://example.com/foo/bar/baz-0.0.2.tar.gz
# - location:
#    git: https://github.com/commercialhaskell/stack.git
#    commit: e7b331f14bcffb8367cd58fbfc8b40ec7642100a
# - location: https://github.com/commercialhaskell/stack/commit/e7b331f14bcffb8367cd58fbfc8b40ec7642100a
#   extra-dep: true
#  subdirs:
#  - auto-update
#  - wai
#
# A package marked 'extra-dep: true' will only be built if demanded by a
# non-dependency (i.e. a user package), and its test suites and benchmarks
# will not be run. This is useful for tweaking upstream packages.
packages:
- .
# Dependency packages to be pulled from upstream that are not in the resolver
# (e.g., acme-missiles-0.3)
extra-deps: []

# Override default flag values for local packages and extra-deps
flags: {}

# Extra package databases containing global packages
extra-package-dbs: []

# Control whether we use the GHC we find on the path
# system-ghc: true
#
# Require a specific version of stack, using version ranges
# require-stack-version: -any # Default
# require-stack-version: ">=1.5"
#
# Override the architecture used by stack, especially useful on Windows
# arch: i386
# arch: x86_64
#
# Extra directories used by stack for building
# extra-include-dirs: [/path/to/dir]
# extra-lib-dirs: [/path/to/dir]
#
# Allow a newer minor version of GHC than the snapshot specifies
# compiler-check: newer-minor
```

**Comment by rikvdkleij** [comment]
Can you try on the command line:
`stack new --bare hspec`

This command is executed by plugin when creating new project.

**Comment by aleqsio** [comment]
Sure, here's stack.yaml after running stack new --bare hspec
```
# This file was automatically generated by 'stack init'
#
# Some commonly used options have been documented as comments in this file.
# For advanced use and comprehensive documentation of the format, please see:
# https://docs.haskellstack.org/en/stable/yaml_configuration/

# Resolver to choose a 'specific' stackage snapshot or a compiler version.
# A snapshot resolver dictates the compiler version and the set of packages
# to be used for project dependencies. For example:
#
# resolver: lts-3.5
# resolver: nightly-2015-09-21
# resolver: ghc-7.10.2
# resolver: ghcjs-0.1.0_ghc-7.10.2
# resolver:
#  name: custom-snapshot
#  location: "./custom-snapshot.yaml"
resolver: lts-9.8

# User packages to be built.
# Various formats can be used as shown in the example below.
#
# packages:
# - some-directory
# - https://example.com/foo/bar/baz-0.0.2.tar.gz
# - location:
#    git: https://github.com/commercialhaskell/stack.git
#    commit: e7b331f14bcffb8367cd58fbfc8b40ec7642100a
# - location: https://github.com/commercialhaskell/stack/commit/e7b331f14bcffb8367cd58fbfc8b40ec7642100a
#   extra-dep: true
#  subdirs:
#  - auto-update
#  - wai
#
# A package marked 'extra-dep: true' will only be built if demanded by a
# non-dependency (i.e. a user package), and its test suites and benchmarks
# will not be run. This is useful for tweaking upstream packages.
packages:
- .
- test
# Dependency packages to be pulled from upstream that are not in the resolver
# (e.g., acme-missiles-0.3)
extra-deps: []

# Override default flag values for local packages and extra-deps
flags: {}

# Extra package databases containing global packages
extra-package-dbs: []

# Control whether we use the GHC we find on the path
# system-ghc: true
#
# Require a specific version of stack, using version ranges
# require-stack-version: -any # Default
# require-stack-version: ">=1.5"
#
# Override the architecture used by stack, especially useful on Windows
# arch: i386
# arch: x86_64
#
# Extra directories used by stack for building
# extra-include-dirs: [/path/to/dir]
# extra-lib-dirs: [/path/to/dir]
#
# Allow a newer minor version of GHC than the snapshot specifies
# compiler-check: newer-minor
```
Here is the full project: https://github.com/aleqsio/alek

**Comment by rikvdkleij** [comment]
@aleqsio Can you import this project with the plugin?

**Comment by codeguru42** [comment]
I am experiencing this same behavior. For this plugin to be useful it shouldn't require creating files manually or issuing CLI commands. I can do all of that without IntelliJ.

**Comment by rikvdkleij** [comment]
I do not understand you. You can import existing Stack project or create new one out-of-box if you have installed Stack.

**Comment by codeguru42** [comment]
I don't have an existing Stack project. When I create a new IntelliJ project using this plugin, i get the same error as the OP. If I am going to create a Stack project using command line tools, this plugin loses much of its usefulness. I might as well just use CLI tools for all of my development.
