### ISSUE TITLE
Stack Docker Support - Longer or Configurable REPL Timeouts?

### ISSUE THREAD

**Issue by SamProtas** [rikvdkleij/intellij-haskell#218]
I need to use stack via docker (https://docs.haskellstack.org/en/stable/docker_integration/) but unfortunately the hard-coded 5 second timeout in intellij-haskell causes the plugin to give up before a command has a chance to run (I think).

After adding the following to my stack.yml

```
docker:
    enable: true
```

and selecting Restart Haskell Stack REPLs. I see the following:

```
6:43 PM	[global-stack-repl] Stack repl could not be started within 5 seconds

6:43 PM	[project-stack-repl-query-metrics-client:exe:query-metrics-client2] Stack repl could not be started within 5 seconds

6:43 PM	[global-stack-repl] No result from Stack repl within 5 seconds. Command was: :set prompt "^IntellijHaskell^\n"
```

I can build my project with `stack build` and use `stack repl` fine from the command line, but there is a noticeable delay caused by what I assume is the docker container starting.

I understand why a timeout is needed, but would you be open to making this configurable somehow? I believe if I could add a couple of seconds to this to account for the initial delay, this would fix my problem.

In case this is helpful:

```
stack --version
Version 1.5.1, Git revision 600c1f01435a10d127938709556c1682ecfd694e (4861 commits) x86_64 hpack-0.17.1
```

Also, just in case you're curious as to why I need docker, I'm attempting to develop a Reflex (GHCJS) app. I can compile it fine with GHC as well, but only via docker as the GHC version of Reflex requires `webkitgtk3` which seems to be broken on MacOS. Since ghci only supports ghc I'm hoping to use a stack.yml with GHC for the editor integration and a separate stack-file just for building the js.

**Comment by rikvdkleij** [comment]
Thanks for reporting!

I will make the REPL timout configurable in `Settings` > `Other Settings` > `Haskell`.

**Comment by SamProtas** [comment]
Thats sounds great! I can test this for you as soon something is available.

I tried editing this plugin's source and recompiling to confirm the fix but I couldn't figure out how to properly set up either the plugin-devkit or sbt.

**Comment by rikvdkleij** [comment]
> Thats sounds great! I can test this for you as soon something is available.

After I have done this fix, I can upload the plugin (which is just a zip file) to GitHub. You can install the plugin by using `Install plugin from disk` in `plugins`

**Comment by rikvdkleij** [comment]
You can download snapshot version from here:
https://github.com/rikvdkleij/intellij-haskell/releases/tag/v1.0.0.beta12-snapshot

Hopefully it works after increasing the REPL timeout.

**Comment by SamProtas** [comment]
Awesome. I probably won't be able to test this today unfortunately, but I should have some (hopefully positive) news by tomorrow.

Thanks for the quick response time.

**Comment by SamProtas** [comment]
The user-defined timeout is working great! I'm now able to use this plugin for editing ghcjs programs on a mac.

I have noticed a couple strange things. In general, the editor hangs more frequently and for longer than usual when working with a non-docker project. My understanding was the editor starts some REPLs in the background and sends them commands. Playing with the REPL directly myself I haven't notice any difference with it being in docker, so I'm a bit surprised I notice a difference with performance. Is there something I'm missing?

Also, I've seen a couple of errors, although the editor integrations still seems to be working fine so I'm not sure if these are just temporary issues that a retry fixes. I pasted in a stack-trace below.

I'm very happy to have your plugin working at all though, so thanks a ton for writing it and fixing my issue so quickly.


Here's the stacktrace:
```
com.intellij.execution.process.ProcessNotCreatedException: Cannot run program "/opt/ghc/8.0.2/bin/ghc" (in directory "/Users/Sam/code/query-metrics/query-metrics-client"): error=2, No such file or directory
java.util.concurrent.ExecutionException: com.intellij.execution.process.ProcessNotCreatedException: Cannot run program "/opt/ghc/8.0.2/bin/ghc" (in directory "/Users/Sam/code/query-metrics/query-metrics-client"): error=2, No such file or directory
	at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:502)
	at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:461)
	at com.google.common.util.concurrent.AbstractFuture$TrustedFuture.get(AbstractFuture.java:78)
	at com.google.common.util.concurrent.Uninterruptibles.getUninterruptibly(Uninterruptibles.java:142)
	at com.google.common.cache.LocalCache$Segment.getAndRecordStats(LocalCache.java:2461)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2425)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2298)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2211)
	at com.google.common.cache.LocalCache.get(LocalCache.java:4154)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4158)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5147)
	at intellij.haskell.external.component.GlobalProjectInfoComponent$.findGlobalProjectInfo(GlobalProjectInfoComponent.scala:83)
	at intellij.haskell.external.component.HaskellComponentsManager$.getSupportedLanguageExtension(HaskellComponentsManager.scala:77)
	at intellij.haskell.annotator.HaskellAnnotator$.findSuggestedLanguageExtension(HaskellAnnotator.scala:177)
	at intellij.haskell.annotator.HaskellAnnotator$.$anonfun$createAnnotations$4(HaskellAnnotator.scala:163)
	at scala.Option.map(Option.scala:146)
	at intellij.haskell.annotator.HaskellAnnotator$.$anonfun$createAnnotations$3(HaskellAnnotator.scala:136)
	at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:241)
	at scala.collection.immutable.List.foreach(List.scala:389)
	at scala.collection.generic.TraversableForwarder.foreach(TraversableForwarder.scala:35)
	at scala.collection.generic.TraversableForwarder.foreach$(TraversableForwarder.scala:35)
	at scala.collection.mutable.ListBuffer.foreach(ListBuffer.scala:44)
	at scala.collection.TraversableLike.flatMap(TraversableLike.scala:241)
	at scala.collection.TraversableLike.flatMap$(TraversableLike.scala:238)
	at scala.collection.AbstractTraversable.flatMap(Traversable.scala:104)
	at intellij.haskell.annotator.HaskellAnnotator$.intellij$haskell$annotator$HaskellAnnotator$$createAnnotations(HaskellAnnotator.scala:132)
	at intellij.haskell.annotator.HaskellAnnotator.apply(HaskellAnnotator.scala:70)
	at intellij.haskell.annotator.HaskellAnnotator.apply(HaskellAnnotator.scala:42)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass.applyRelevant(ExternalToolPass.java:190)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass.access$700(ExternalToolPass.java:47)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass$1.lambda$run$0(ExternalToolPass.java:164)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1161)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass$1.run(ExternalToolPass.java:160)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:337)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:327)
	at com.intellij.util.ui.update.MergingUpdateQueue.lambda$flush$1(MergingUpdateQueue.java:277)
	at com.intellij.util.ui.update.MergingUpdateQueue.flush(MergingUpdateQueue.java:291)
	at com.intellij.util.ui.update.MergingUpdateQueue.run(MergingUpdateQueue.java:246)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:246)
	at com.intellij.util.Alarm$Request.runSafely(Alarm.java:417)
	at com.intellij.util.Alarm$Request.access$700(Alarm.java:344)
	at com.intellij.util.Alarm$Request$1.run(Alarm.java:384)
	at com.intellij.util.Alarm$Request.run(Alarm.java:395)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:237)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:212)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.intellij.execution.process.ProcessNotCreatedException: Cannot run program "/opt/ghc/8.0.2/bin/ghc" (in directory "/Users/Sam/code/query-metrics/query-metrics-client"): error=2, No such file or directory
	at com.intellij.execution.configurations.GeneralCommandLine.createProcess(GeneralCommandLine.java:391)
	at com.intellij.execution.process.OSProcessHandler.<init>(OSProcessHandler.java:45)
	at com.intellij.execution.process.CapturingProcessHandler.<init>(CapturingProcessHandler.java:38)
	at intellij.haskell.external.execution.CommandLine$.createProcessHandler(CommandLine.scala:76)
	at intellij.haskell.external.execution.CommandLine$.run(CommandLine.scala:40)
	at intellij.haskell.external.execution.CommandLine$.runProgram(CommandLine.scala:36)
	at intellij.haskell.external.component.GlobalProjectInfoComponent$$anon$1.$anonfun$getSupportedLanguageExtensions$1(GlobalProjectInfoComponent.scala:65)
	at scala.Option.flatMap(Option.scala:171)
	at intellij.haskell.external.component.GlobalProjectInfoComponent$$anon$1.getSupportedLanguageExtensions(GlobalProjectInfoComponent.scala:59)
	at intellij.haskell.external.component.GlobalProjectInfoComponent$$anon$1.createGlobalProjectInfo(GlobalProjectInfoComponent.scala:53)
	at intellij.haskell.external.component.GlobalProjectInfoComponent$$anon$1.load(GlobalProjectInfoComponent.scala:40)
	at intellij.haskell.external.component.GlobalProjectInfoComponent$$anon$1.load(GlobalProjectInfoComponent.scala:37)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3716)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2424)
	... 44 more
Caused by: java.io.IOException: Cannot run program "/opt/ghc/8.0.2/bin/ghc" (in directory "/Users/Sam/code/query-metrics/query-metrics-client"): error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at com.intellij.execution.configurations.GeneralCommandLine.startProcess(GeneralCommandLine.java:420)
	at com.intellij.execution.configurations.GeneralCommandLine.createProcess(GeneralCommandLine.java:387)
	... 57 more
Caused by: java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 59 more
```

`which ghc` returns nothing on my machine and `/opt/ghc/8.0.2/bin/ghc` doesn't exist.

**Comment by rikvdkleij** [comment]
It seems that ` stack path --compiler-exe` does not give right result. 

Part of Stack Docker integration documentation:
```
Please note that in a docker-enabled configuration, stack uses the GHC installed in the Docker container by default. To use a compiler installed by stack, add

system-ghc: false
```

**Comment by SamProtas** [comment]
Thanks for the tip, here's my "docker specific" stack section now:

```
docker:
    enable: true
    run-args: ['--ulimit', 'nofile=5000:5000']

system-ghc: false
```

All seems good and maybe a bit more performant? I'm not sure if that makes sense, but at least it initially seems so.

I think we can consider this issue closed. Thanks again for the quick update to support my request.
