### ISSUE TITLE
Exception: Read access is allowed from event dispatch thread or inside read-action only

### ISSUE THREAD

**Issue by chris-martin** [rikvdkleij/intellij-haskell#228]
I just updated to 1.0.0-beta12 and I got a popup reporting this exception:

```
Read access is allowed from event dispatch thread or inside read-action only (see com.intellij.openapi.application.Application.runReadAction())
Details: Current thread: Thread[ApplicationImpl pooled thread 49,4,main] 1625781927
; dispatch thread: false; isDispatchThread(): false
SystemEventQueueThread: Thread[AWT-EventQueue-0 2017.2.4#IC-172.4155.36 IDEA, eap:false, os:Linux 4.13.4, java-version:JetBrains s.r.o 1.8.0_152-release-970-b2,6,main] 335359547
java.lang.Throwable
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:150)
	at com.intellij.openapi.application.impl.ApplicationImpl.assertReadAccessAllowed(ApplicationImpl.java:1075)
	at com.intellij.openapi.module.impl.ModuleManagerImpl.moduleDependencyComparator(ModuleManagerImpl.java:531)
	at com.intellij.openapi.module.ModuleUtilCore.findModuleForPsiElement(ModuleUtilCore.java:112)
	at intellij.haskell.util.HaskellProjectUtil$.findModule(HaskellProjectUtil.scala:125)
	at intellij.haskell.external.component.LoadComponent$.$anonfun$load$1(LoadComponent.scala:58)
	at intellij.haskell.external.component.LoadComponent$.$anonfun$load$1$adapted(LoadComponent.scala:56)
	at scala.Option.foreach(Option.scala:257)
	at intellij.haskell.external.component.LoadComponent$.load(LoadComponent.scala:56)
	at intellij.haskell.external.component.HaskellComponentsManager$.loadHaskellFile(HaskellComponentsManager.scala:96)
	at intellij.haskell.annotator.HaskellAnnotator.doAnnotate(HaskellAnnotator.scala:66)
	at intellij.haskell.annotator.HaskellAnnotator.doAnnotate(HaskellAnnotator.scala:42)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass.doAnnotate(ExternalToolPass.java:211)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass.access$500(ExternalToolPass.java:47)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass$1.run(ExternalToolPass.java:158)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:337)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:327)
	at com.intellij.util.ui.update.MergingUpdateQueue.lambda$flush$1(MergingUpdateQueue.java:277)
	at com.intellij.util.ui.update.MergingUpdateQueue.flush(MergingUpdateQueue.java:291)
	at com.intellij.util.ui.update.MergingUpdateQueue.run(MergingUpdateQueue.java:246)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:246)
	at com.intellij.util.Alarm$Request.runSafely(Alarm.java:417)
	at com.intellij.util.Alarm$Request.access$700(Alarm.java:344)
	at com.intellij.util.Alarm$Request$1.run(Alarm.java:384)
	at com.intellij.util.Alarm$Request.run(Alarm.java:395)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:237)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:212)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

Everything still seems to be working, though, as far as I can tell so far.

**Comment by rikvdkleij** [comment]
Oops, thanks for reporting!

> Everything still seems to be working, though, as far as I can tell so far.

:sweat_smile:

**Comment by ice1000** [comment]
```

Details: Current thread: Thread[scala-execution-context-global-302,5,Idea Thread Group] 965846287
; dispatch thread: false; isDispatchThread(): false
SystemEventQueueThread: Thread[AWT-EventQueue-0 2018.3.1#IC-183.4588.3 IDEA, eap:true, os:Windows 10 10.0, java-version:JetBrains s.r.o 1.8.0_152-release-1343-b16,6,Idea Thread Group] 1926519178

java.lang.Throwable: Read access is allowed from event dispatch thread or inside read-action only (see com.intellij.openapi.application.Application.runReadAction())
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:156)
	at com.intellij.openapi.application.impl.ApplicationImpl.assertReadAccessAllowed(ApplicationImpl.java:1090)
	at com.intellij.psi.impl.source.tree.TreeElement.assertReadAccessAllowed(TreeElement.java:426)
	at com.intellij.psi.impl.source.tree.CompositeElement.textToCharArray(CompositeElement.java:255)
	at com.intellij.psi.impl.source.tree.CompositeElement.getText(CompositeElement.java:225)
	at com.intellij.extapi.psi.ASTDelegatePsiElement.getText(ASTDelegatePsiElement.java:146)
	at intellij.haskell.psi.impl.HaskellPsiImplUtil$.getName(HaskellPsiImplUtil.scala:93)
	at intellij.haskell.psi.impl.HaskellPsiImplUtil.getName(HaskellPsiImplUtil.scala)
	at intellij.haskell.psi.impl.HaskellModidImpl.getName(HaskellModidImpl.java:46)
	at intellij.haskell.psi.impl.HaskellPsiImplUtil$.$anonfun$getModuleName$1(HaskellPsiImplUtil.scala:402)
	at scala.Option.map(Option.scala:146)
	at intellij.haskell.psi.impl.HaskellPsiImplUtil$.getModuleName(HaskellPsiImplUtil.scala:402)
	at intellij.haskell.psi.impl.HaskellPsiImplUtil.getModuleName(HaskellPsiImplUtil.scala)
	at intellij.haskell.psi.impl.HaskellImportDeclarationImpl.getModuleName(HaskellImportDeclarationImpl.java:66)
	at intellij.haskell.editor.HaskellCompletionContributor$.$anonfun$getLocalTopLevelLookupElements$3(HaskellCompletionContributor.scala:609)
	at intellij.haskell.editor.HaskellCompletionContributor$.$anonfun$getLocalTopLevelLookupElements$3$adapted(HaskellCompletionContributor.scala:609)
	at scala.collection.Iterator.find(Iterator.scala:989)
	at scala.collection.Iterator.find$(Iterator.scala:986)
	at scala.collection.AbstractIterator.find(Iterator.scala:1425)
	at scala.collection.IterableLike.find(IterableLike.scala:77)
	at scala.collection.IterableLike.find$(IterableLike.scala:76)
	at scala.collection.AbstractIterable.find(Iterable.scala:54)
	at intellij.haskell.editor.HaskellCompletionContributor$.$anonfun$getLocalTopLevelLookupElements$2(HaskellCompletionContributor.scala:609)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:233)
	at scala.collection.immutable.List.foreach(List.scala:388)
	at scala.collection.generic.TraversableForwarder.foreach(TraversableForwarder.scala:34)
	at scala.collection.generic.TraversableForwarder.foreach$(TraversableForwarder.scala:34)
	at scala.collection.mutable.ListBuffer.foreach(ListBuffer.scala:43)
	at scala.collection.TraversableLike.map(TraversableLike.scala:233)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:226)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at intellij.haskell.editor.HaskellCompletionContributor$.intellij$haskell$editor$HaskellCompletionContributor$$getLocalTopLevelLookupElements(HaskellCompletionContributor.scala:605)
	at intellij.haskell.editor.HaskellCompletionContributor.$anonfun$getAvailableLookupElements$1(HaskellCompletionContributor.scala:395)
	at intellij.haskell.editor.HaskellCompletionContributor$.$anonfun$useAvailableModuleIdentifiers$6(HaskellCompletionContributor.scala:441)
	at scala.util.Success.$anonfun$map$1(Try.scala:251)
	at scala.util.Success.map(Try.scala:209)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:288)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:29)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:29)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

Still happens in the beta build (the one I built myself, from #331, which should be very new)

**Comment by ice1000** [comment]
Ooops, it's in another position.

**Comment by rikvdkleij** [comment]
> Ooops, it's in another position.

What do you mean?

**Comment by ice1000** [comment]
> Wait, you just mean the cause is different location.

Yeah. Sorry for my English but can you fix this? I suppose it's easy to fix.

**Comment by ice1000** [comment]
Wow! Happy to hear that.

**Comment by Sir4ur0n** [comment]
Hi guys, any progress here? I still get this exception in beta 44.

**Comment by rikvdkleij** [comment]
@Sir4ur0n  It is impossible that your error is the same as originally in this issue  😄 

Can you give me the stacktrace so I can see where a readaction is missing?

**Comment by Sir4ur0n** [comment]
```

Details: Current thread: Thread[ApplicationImpl pooled thread 239,4,Idea Thread Group] 1780781522
; dispatch thread: false; isDispatchThread(): false
SystemEventQueueThread: Thread[AWT-EventQueue-0,6,Idea Thread Group] 545212905

java.lang.Throwable: Read access is allowed from event dispatch thread or inside read-action only (see com.intellij.openapi.application.Application.runReadAction())
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:156)
	at com.intellij.openapi.application.impl.ApplicationImpl.assertReadAccessAllowed(ApplicationImpl.java:1090)
	at com.intellij.openapi.fileEditor.impl.FileDocumentManagerImpl.getDocument(FileDocumentManagerImpl.java:172)
	at com.intellij.psi.AbstractFileViewProvider.getDocument(AbstractFileViewProvider.java:194)
	at com.intellij.psi.AbstractFileViewProvider$VirtualFileContent.getText(AbstractFileViewProvider.java:484)
	at com.intellij.psi.AbstractFileViewProvider.getContents(AbstractFileViewProvider.java:174)
	at com.intellij.psi.impl.source.PsiFileImpl.getText(PsiFileImpl.java:279)
	at intellij.haskell.action.HindentReformatAction$.$anonfun$format$1(HindentReformatAction.scala:68)
	at intellij.haskell.util.ScalaUtil$$anon$3.call(ScalaUtil.scala:46)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.call(ApplicationImpl.java:337)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by rikvdkleij** [comment]
@Sir4ur0n Thanks!

**Comment by rikvdkleij** [comment]
Please reopen when it's still an issue.
