### ISSUE TITLE
Unhandled exception in IDEA 2017.3

### ISSUE THREAD

**Issue by csi-adziahel** [rikvdkleij/intellij-haskell#241]
Repro: open up a project with hlint issues, I guess
Backtrace: <details>
```
Assertion failed
java.lang.Throwable: Assertion failed
	at com.intellij.openapi.diagnostic.Logger.assertTrue(Logger.java:172)
	at com.intellij.openapi.diagnostic.Logger.assertTrue(Logger.java:181)
	at com.intellij.codeInspection.LocalQuickFixOnPsiElement.<init>(LocalQuickFixOnPsiElement.java:40)
	at intellij.haskell.inspection.HLintQuickfix.<init>(HLintQuickfix.scala:29)
	at intellij.haskell.inspection.HLintInspectionTool.intellij$haskell$inspection$HLintInspectionTool$$createQuickfix(HLintInspectionTool.scala:93)
	at intellij.haskell.inspection.HLintInspectionTool$$anon$1$$anon$2.run(HLintInspectionTool.scala:68)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:912)
	at intellij.haskell.inspection.HLintInspectionTool$$anon$1.$anonfun$call$7(HLintInspectionTool.scala:63)
	at scala.runtime.java8.JFunction1$mcVI$sp.apply(JFunction1$mcVI$sp.java:12)
	at scala.Option.map(Option.scala:146)
	at intellij.haskell.inspection.HLintInspectionTool$$anon$1.$anonfun$call$6(HLintInspectionTool.scala:60)
	at intellij.haskell.inspection.HLintInspectionTool$$anon$1.$anonfun$call$6$adapted(HLintInspectionTool.scala:59)
	at scala.Option.flatMap(Option.scala:171)
	at intellij.haskell.inspection.HLintInspectionTool$$anon$1.$anonfun$call$5(HLintInspectionTool.scala:59)
	at scala.Option.flatMap(Option.scala:171)
	at intellij.haskell.inspection.HLintInspectionTool$$anon$1.$anonfun$call$4(HLintInspectionTool.scala:58)
	at scala.Option.flatMap(Option.scala:171)
	at intellij.haskell.inspection.HLintInspectionTool$$anon$1.$anonfun$call$3(HLintInspectionTool.scala:57)
	at scala.collection.TraversableLike$WithFilter.$anonfun$flatMap$2(TraversableLike.scala:770)
	at scala.collection.immutable.List.foreach(List.scala:389)
	at scala.collection.TraversableLike$WithFilter.flatMap(TraversableLike.scala:769)
	at intellij.haskell.inspection.HLintInspectionTool$$anon$1.call(HLintInspectionTool.scala:54)
	at intellij.haskell.inspection.HLintInspectionTool$$anon$1.call(HLintInspectionTool.scala:48)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.call(ApplicationImpl.java:338)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```
</details>

**Comment by rikvdkleij** [comment]
Thanks for reporting! I did not see this error earlier but I will take a look of what can go wrong 😄 

Btw, do you still use the plugin?

**Comment by csi-adziahel** [comment]
> Btw, do you still use the plugin?

@rikvdkleij of course. AFAIK this is only plugin that takes care of dependencies' source code, which is a major selling point for me.

**Comment by rikvdkleij** [comment]
Great to hear!

Would you like to test a preliminary release of plugin? I do not know when I will release it, hopefully soon. It's not a release with more features but focused on robustness and responsiveness.

**Comment by csi-adziahel** [comment]
> Would you like to test a preliminary release of plugin?

Ya, would love to. You could distribute it through http://www.jetbrains.org/intellij/sdk/docs/plugin_repository/custom_channels.html BTW.

**Comment by rikvdkleij** [comment]
Great!

> You could distribute it through http://www.jetbrains.org/intellij/sdk/docs/plugin_repository/custom_channels.html BTW.

Good idea, I will use the `alpha` channel.

**Comment by rikvdkleij** [comment]
I have released new version of plugin https://github.com/rikvdkleij/intellij-haskell/releases/tag/v1.0.0-beta14
It's also uploaded it to Alpha channel of Jetbrains plugin repo but that can take some time before it's published

**Comment by rikvdkleij** [comment]
@csi-adziahel I do not understand how to configure IntelliJ to load plugins from the Alpha channel. Do you know how? 

Also pasting the URL from the plugin as plugin repo like
https://plugins.jetbrains.com/plugin/8258-intellij-haskell/update/46587
does not work.

Do you know how?

The plugin is not yet approved.

**Comment by rikvdkleij** [comment]
@csi-adziahel O wait, it's explained in the link you gave:
`http://www.jetbrains.org/intellij/sdk/docs/plugin_repository/custom_channels.html B`

**Comment by rikvdkleij** [comment]
Please reopen when it's still an issue.
