### ISSUE TITLE
NullPointerException when trying to create a Haskell Stack Test Runner

### ISSUE THREAD

**Issue by amrhassan** [rikvdkleij/intellij-haskell#269]
Hello,

I get this exception when I try to create a new test runner Run Configuration. I'm using the latest Intellij 2018.1.1 Community Edition.

```
java.lang.NullPointerException
com.intellij.util.xmlb.XmlSerializationException: java.lang.NullPointerException
	at com.intellij.util.xmlb.XmlSerializer.serializeInto(XmlSerializer.java:123)
	at com.intellij.util.xmlb.XmlSerializer.serializeInto(XmlSerializer.java:107)
	at intellij.haskell.runconfig.HaskellStackConfigurationBase.writeExternal(HaskellStackConfigurationBase.scala:25)
	at com.intellij.execution.configurations.ModuleBasedConfiguration.clone(ModuleBasedConfiguration.java:128)
	at com.intellij.execution.configurations.ModuleBasedConfiguration.clone(ModuleBasedConfiguration.java:26)
	at com.intellij.execution.configurations.ConfigurationFactory.createConfiguration(ConfigurationFactory.java:38)
	at com.intellij.execution.impl.RunManagerImpl.createConfiguration(RunManagerImpl.kt:154)
	at com.intellij.execution.impl.RunConfigurable.createNewConfiguration(RunConfigurable.kt:978)
	at com.intellij.execution.impl.RunConfigurable$MyToolbarAddAction$showAddPopup$popup$1.consume(RunConfigurable.kt:1011)
	at com.intellij.execution.impl.RunConfigurable$MyToolbarAddAction$showAddPopup$popup$1.consume(RunConfigurable.kt:984)
	at com.intellij.execution.impl.NewRunConfigurationPopup$1$1.onChosen(NewRunConfigurationPopup.java:105)
	at com.intellij.execution.impl.NewRunConfigurationPopup$1$1.onChosen(NewRunConfigurationPopup.java:90)
	at com.intellij.ui.popup.list.ListPopupImpl._handleSelect(ListPopupImpl.java:390)
	at com.intellij.ui.popup.list.ListPopupImpl.handleSelect(ListPopupImpl.java:342)
	at com.intellij.ui.popup.list.ListPopupImpl$MyMouseListener.mouseReleased(ListPopupImpl.java:501)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:290)
	at java.awt.Component.processMouseEvent(Component.java:6541)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3325)
	at com.intellij.ui.popup.list.ListPopupImpl$MyList.processMouseEvent(ListPopupImpl.java:552)
	at java.awt.Component.processEvent(Component.java:6306)
	at java.awt.Container.processEvent(Container.java:2237)
	at java.awt.Component.dispatchEventImpl(Component.java:4897)
	at java.awt.Container.dispatchEventImpl(Container.java:2295)
	at java.awt.Component.dispatchEvent(Component.java:4719)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4889)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4526)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4467)
	at java.awt.Container.dispatchEventImpl(Container.java:2281)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4719)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:737)
	at java.awt.EventQueue$4.run(EventQueue.java:735)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:779)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:716)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:395)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:109)
	at java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:190)
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:235)
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:233)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:233)
	at java.awt.Dialog.show(Dialog.java:1077)
	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog.show(DialogWrapperPeerImpl.java:694)
	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl.show(DialogWrapperPeerImpl.java:427)
	at com.intellij.openapi.ui.DialogWrapper.invokeShow(DialogWrapper.java:1682)
	at com.intellij.openapi.ui.DialogWrapper.show(DialogWrapper.java:1631)
	at com.intellij.execution.actions.EditRunConfigurationsAction.actionPerformed(EditRunConfigurationsAction.java:47)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:220)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:237)
	at com.intellij.ui.popup.PopupFactoryImpl$ActionPopupStep.performAction(PopupFactoryImpl.java:908)
	at com.intellij.ui.popup.PopupFactoryImpl$ActionPopupStep.performAction(PopupFactoryImpl.java:898)
	at com.intellij.ui.popup.PopupFactoryImpl$ActionPopupStep.lambda$onChosen$0(PopupFactoryImpl.java:892)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:195)
	at com.intellij.ui.popup.AbstractPopup.lambda$dispose$7(AbstractPopup.java:1398)
	at com.intellij.util.ui.UIUtil.invokeLaterIfNeeded(UIUtil.java:2850)
	at com.intellij.ide.IdeEventQueue.ifFocusEventsInTheQueue(IdeEventQueue.java:173)
	at com.intellij.ide.IdeEventQueue.executeWhenAllFocusEventsLeftTheQueue(IdeEventQueue.java:132)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.doWhenFocusSettlesDown(FocusManagerImpl.java:190)
	at com.intellij.openapi.wm.impl.IdeFocusManagerImpl.doWhenFocusSettlesDown(IdeFocusManagerImpl.java:56)
	at com.intellij.ui.popup.AbstractPopup.dispose(AbstractPopup.java:1392)
	at com.intellij.ui.popup.WizardPopup.dispose(WizardPopup.java:160)
	at com.intellij.ui.popup.list.ListPopupImpl.dispose(ListPopupImpl.java:307)
	at com.intellij.ui.popup.PopupFactoryImpl$ActionGroupPopup.dispose(PopupFactoryImpl.java:338)
	at com.intellij.openapi.util.Disposer$1.execute(Disposer.java:48)
	at com.intellij.openapi.util.Disposer$1.execute(Disposer.java:44)
	at com.intellij.openapi.util.objectTree.ObjectNode$1.execute(ObjectNode.java:138)
	at com.intellij.openapi.util.objectTree.ObjectNode$1.execute(ObjectNode.java:107)
	at com.intellij.openapi.util.objectTree.ObjectTree.executeActionWithRecursiveGuard(ObjectTree.java:169)
	at com.intellij.openapi.util.objectTree.ObjectNode.execute(ObjectNode.java:107)
	at com.intellij.openapi.util.objectTree.ObjectTree.executeAll(ObjectTree.java:144)
	at com.intellij.openapi.util.Disposer.dispose(Disposer.java:129)
	at com.intellij.openapi.util.Disposer.dispose(Disposer.java:125)
	at com.intellij.ui.popup.WizardPopup.disposeAllParents(WizardPopup.java:263)
	at com.intellij.ui.popup.list.ListPopupImpl.handleNextStep(ListPopupImpl.java:442)
	at com.intellij.ui.popup.list.ListPopupImpl._handleSelect(ListPopupImpl.java:396)
	at com.intellij.ui.popup.list.ListPopupImpl.handleSelect(ListPopupImpl.java:342)
	at com.intellij.ui.popup.PopupFactoryImpl$ActionGroupPopup.handleSelect(PopupFactoryImpl.java:358)
	at com.intellij.ui.popup.list.ListPopupImpl$MyMouseListener.mouseReleased(ListPopupImpl.java:501)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:290)
	at java.awt.Component.processMouseEvent(Component.java:6541)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3325)
	at com.intellij.ui.popup.list.ListPopupImpl$MyList.processMouseEvent(ListPopupImpl.java:552)
	at java.awt.Component.processEvent(Component.java:6306)
	at java.awt.Container.processEvent(Container.java:2237)
	at java.awt.Component.dispatchEventImpl(Component.java:4897)
	at java.awt.Container.dispatchEventImpl(Container.java:2295)
	at java.awt.Component.dispatchEvent(Component.java:4719)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4889)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4526)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4467)
	at java.awt.Container.dispatchEventImpl(Container.java:2281)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4719)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:737)
	at java.awt.EventQueue$4.run(EventQueue.java:735)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:779)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:716)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:395)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.NullPointerException
	at intellij.haskell.external.component.HaskellComponentsManager$.$anonfun$findCabalInfos$1(HaskellComponentsManager.scala:92)
	at scala.Option.map(Option.scala:146)
	at intellij.haskell.external.component.HaskellComponentsManager$.findCabalInfos(HaskellComponentsManager.scala:92)
	at intellij.haskell.runconfig.test.HaskellTestConfiguration.getTestSuiteTargetNames(HaskellTestConfiguration.scala:21)
	at intellij.haskell.runconfig.test.HaskellTestConfiguration.getTestSuiteTargetName(HaskellTestConfiguration.scala:30)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.util.xmlb.PropertyAccessor.read(PropertyAccessor.java:52)
	at com.intellij.util.xmlb.OptionTagBinding.serialize(OptionTagBinding.java:42)
	at com.intellij.util.xmlb.BasePrimitiveBinding.serialize(BasePrimitiveBinding.java:41)
	at com.intellij.util.xmlb.BeanBinding.serializeInto(BeanBinding.java:103)
	at com.intellij.util.xmlb.XmlSerializer.serializeInto(XmlSerializer.java:117)
	... 125 more
```

**Comment by rikvdkleij** [comment]
Thanks for reporting! 

Do you know if this problem also occurred in IntelliJ 2017?

**Comment by amrhassan** [comment]
I think not but I'm not sure. I was not using it for a while.

**Comment by rikvdkleij** [comment]
Hi,

Thanks for reporting. It looks like plugin could not read Cabal file.

Cheers,
Rik

**Comment by yunti** [comment]
Thanks for your reply, I'm not clear how to resolve the issue and why the plugin couldn't see (or read) a cabal file?  The project is setup with the Project SDK specified as Haskell Tool Stack (1.7.1) in the project structure.  And a normal project .cabal file in the project folder.  (building and exec from the terminal for the project work as expected).
Thanks again if you can help clarify where the issue might be.

**Comment by yunti** [comment]
Thanks for your reply.  The issue seems to be with the simple project template in stack - the standard one works as expected.

**Comment by rikvdkleij** [comment]
@yunti Which one did you use? The plugin use `hspec` template when creating new project inside IntelliJ.

**Comment by rikvdkleij** [comment]
@amrhassan It looks like your error was caused by the same reason.

**Comment by yunti** [comment]
Sorry for the confusing comments.  I've been starting projects from the command line with `stack new projectname`.  I can now get it to work with a simple project too (although each time I have to rebuild the hoogle database -might need a separate issue).  When setting up the original simple project I made an error in the wizard and didn't select the haskell tool kit - I had to set this up afterwards. Perhaps that was the source of the error somehow.

**Comment by rikvdkleij** [comment]
Okay, thanks for your explanation.

> although each time I have to rebuild the hoogle database -might need a separate issue)

It's an informational message to rebuild the Hoogle db. You do not have to.

**Comment by yunti** [comment]
ok thanks

**Comment by Sir4ur0n** [comment]
I guess we can close this issue?

**Comment by rikvdkleij** [comment]
Please reopen if this is still an issue in latest beta.
