### ISSUE TITLE
Documentation should mention hindent/stylish-haskell path must be absolute

### ISSUE THREAD

**Issue by Sir4ur0n** [rikvdkleij/intellij-haskell#285]
Hello,

I had trouble using this plugin for some time when I configured in `Preferences / Other Settings / Haskell` a relative path for Hindent and Stylish-haskell: `~/.local/bin/hindent` and `~/.local/bin/stylish-haskell`.

After I switched to absolute path this works like a charm.

Maybe this should be pointed out in the documentation, this would have saved me some trouble.

FYI when using a relative path I get this kind of error in Intellij:
```
Cannot run program "~/.local/bin/hindent": error=2, No such file or directory
java.io.IOException: Cannot run program "~/.local/bin/hindent": error=2, No such file or directory
    at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
    at intellij.haskell.action.HindentFormatAction$.intellij$haskell$action$HindentFormatAction$$writeToHindent(HindentFormatAction.scala:104)
    at intellij.haskell.action.HindentFormatAction$$anon$1.call(HindentFormatAction.scala:71)
    at intellij.haskell.action.HindentFormatAction$$anon$1.call(HindentFormatAction.scala:67)
    at com.intellij.openapi.application.impl.ApplicationImpl$2.call(ApplicationImpl.java:328)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: error=2, No such file or directory
    at java.lang.UNIXProcess.forkAndExec(Native Method)
    at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
    at java.lang.ProcessImpl.start(ProcessImpl.java:134)
    at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
    ... 8 more
```

```
Cannot run program "~/.local/bin/stylish-haskell" (in directory "..."): error=2, No such file or directory
com.intellij.execution.process.ProcessNotCreatedException: Cannot run program "~/.local/bin/stylish-haskell" (in directory "..."): error=2, No such file or directory
    at com.intellij.execution.configurations.GeneralCommandLine.createProcess(GeneralCommandLine.java:395)
    at com.intellij.execution.process.OSProcessHandler.startProcess(OSProcessHandler.java:51)
    at com.intellij.execution.process.OSProcessHandler.<init>(OSProcessHandler.java:44)
    at com.intellij.execution.process.CapturingProcessHandler.<init>(CapturingProcessHandler.java:35)
    at intellij.haskell.external.execution.CommandLine$.createProcessHandler(CommandLine.scala:77)
    at intellij.haskell.external.execution.CommandLine$.run(CommandLine.scala:41)
    at intellij.haskell.external.execution.CommandLine$.runProgram(CommandLine.scala:37)
    at intellij.haskell.action.StylishHaskellFormatAction$$anon$1.call(StylishHaskellFormatAction.scala:54)
    at intellij.haskell.action.StylishHaskellFormatAction$$anon$1.call(StylishHaskellFormatAction.scala:52)
    at com.intellij.openapi.application.impl.ApplicationImpl$2.call(ApplicationImpl.java:328)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: Cannot run program "~/.local/bin/stylish-haskell" (in directory "..."): error=2, No such file or directory
    at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
    at com.intellij.execution.configurations.GeneralCommandLine.startProcess(GeneralCommandLine.java:423)
    at com.intellij.execution.configurations.GeneralCommandLine.createProcess(GeneralCommandLine.java:391)
    ... 13 more
Caused by: java.io.IOException: error=2, No such file or directory
    at java.lang.UNIXProcess.forkAndExec(Native Method)
    at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
    at java.lang.ProcessImpl.start(ProcessImpl.java:134)
    at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
    ... 15 more
```

**Comment by rikvdkleij** [comment]
In latest beta versions all Haskell tools are automatically installed in IntelliJ sandbox. So this issue is not relevant anymore.

If you want, you give the latest beta a try, https://github.com/rikvdkleij/intellij-haskell/releases/tag/v1.0.0-beta17

**Comment by Sir4ur0n** [comment]
Sounds perfect to me, I'm closing this issue then 😄
