### ISSUE TITLE
Go To Definition and Quick Docs don't work

### ISSUE THREAD

**Issue by oleksandr-oksenenko** [rikvdkleij/intellij-haskell#292]
Plugin's Go To Definition, Quick Docs don't work for me :(

Firstly i got the exception: 

```
java.nio.charset.MalformedInputException: Input length = 1                                                                                                                                                                              
     at java.nio.charset.CoderResult.throwException(CoderResult.java:281)                                                                                                                                                                
     at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:339)                                                                                                                                                                        
     at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)                                                                                                                                                                            
     at java.io.InputStreamReader.read(InputStreamReader.java:184)                                                                                                                                                                       
     at java.io.BufferedReader.fill(BufferedReader.java:161)                                                                                                                                                                             
     at java.io.BufferedReader.readLine(BufferedReader.java:324)                                                                                                                                                                         
     at java.io.BufferedReader.readLine(BufferedReader.java:389)                                                                                                                                                                         
     at scala.io.BufferedSource$BufferedLineIterator.hasNext(BufferedSource.scala:70)                                                                                                                                                    
     at scala.collection.Iterator.foreach(Iterator.scala:929)                                                                                                                                                                            
     at scala.collection.Iterator.foreach$(Iterator.scala:929)                                                                                                                                                                           
     at scala.collection.AbstractIterator.foreach(Iterator.scala:1417)                                                                                                                                                                   
     at intellij.haskell.external.repl.StackRepl.$anonfun$start$4(StackRepl.scala:185)                                                                                                                                                   
     at intellij.haskell.external.repl.StackRepl.$anonfun$start$4$adapted(StackRepl.scala:185)                                                                                                                                           
     at scala.sys.process.ProcessBuilderImpl$Simple.$anonfun$run$3(ProcessBuilderImpl.scala:76)                                                                                                                                          
     at scala.sys.process.ProcessImpl$Spawn$$anon$1.run(ProcessImpl.scala:23)                                                                                                                                                            
2018-08-07 10:27:20,599 [55699894]  ERROR - llij.ide.plugins.PluginManager - IntelliJ IDEA 2018.2  Build #IU-182.3684.101                                                                                                               
2018-08-07 10:27:20,600 [55699895]  ERROR - llij.ide.plugins.PluginManager - JDK: 1.8.0_172                                                                                                                                             
2018-08-07 10:27:20,600 [55699895]  ERROR - llij.ide.plugins.PluginManager - VM: OpenJDK 64-Bit Server VM                                                                                                                               
2018-08-07 10:27:20,600 [55699895]  ERROR - llij.ide.plugins.PluginManager - Vendor: Oracle Corporation                                                                                                                                 
2018-08-07 10:27:20,600 [55699895]  ERROR - llij.ide.plugins.PluginManager - OS: Linux                                                                                                                                                  
2018-08-07 10:27:20,600 [55699895]  ERROR - llij.ide.plugins.PluginManager - Last Action: QuickJavaDoc
```

Then all calls to Go To Definition and Quick Docs result in

```
10:27 AM	[project-stack-repl-haskell-playground:exe:haskell-playground-exe] No result from Stack repl within 5 seconds. Command was: :info someFunc
```

I created the project from default template via `stack new <project_name>`.
I use `1.0.0-beta12` version of the plugin.

**Comment by oleksandr-oksenenko** [comment]
Nevermidnd, i found out that i'm not using the latest version of the plugin. Updated, it works now.
Sorry for making noise :)
