### ISSUE TITLE
DeserializationException on startup

### ISSUE THREAD

**Issue by declension** [rikvdkleij/intellij-haskell#322]
### Steps to replicate
 * Open an existing Haskell project from Intellij. Only happens on some projects (more than one, or at least more happens on more than one different installation). I'll keep an eye on it to try to find some correlations.
 * Wait for auto-build / Hoogle download (note, no human interaction at this point).

### Expected
 * Project to auto build / Hoogle database to sort itself out.
 * No stack traces to be reported.

### Actual
 * Logs report ```Hoogle database does not exist. Hoogle database can be created by menu option `Tools`/`Haskell`/`(Re)Build Hoogle database` ```
 * Then, this pops up:
```
spray.json.DeserializationException: Expected String as JsString, but got ["Main"]
	at spray.json.package$.deserializationError(package.scala:23)
	at spray.json.ProductFormats.fromField(ProductFormats.scala:62)
	at spray.json.ProductFormats.fromField$(ProductFormats.scala:50)
	at intellij.haskell.external.component.HLintComponent$HlintJsonProtocol$.fromField(HLintComponent.scala:54)
	at spray.json.ProductFormatsInstances$$anon$12.read(ProductFormatsInstances.scala:375)
	at spray.json.ProductFormatsInstances$$anon$12.read(ProductFormatsInstances.scala:356)
	at spray.json.JsValue.convertTo(JsValue.scala:31)
	at spray.json.CollectionFormats$$anon$4.$anonfun$read$4(CollectionFormats.scala:89)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
	at scala.collection.Iterator.foreach(Iterator.scala:929)
	at scala.collection.Iterator.foreach$(Iterator.scala:929)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1417)
	at scala.collection.IterableLike.foreach(IterableLike.scala:71)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:70)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at scala.collection.TraversableLike.map(TraversableLike.scala:234)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at spray.json.CollectionFormats$$anon$4.read(CollectionFormats.scala:89)
	at spray.json.CollectionFormats$$anon$4.read(CollectionFormats.scala:86)
	at spray.json.JsValue.convertTo(JsValue.scala:31)
	at intellij.haskell.external.component.HLintComponent$.deserializeHLintInfo(HLintComponent.scala:65)
	at intellij.haskell.external.component.HLintComponent$.$anonfun$check$1(HLintComponent.scala:45)
	at scala.Option.map(Option.scala:146)
	at intellij.haskell.external.component.HLintComponent$.check(HLintComponent.scala:36)
	at intellij.haskell.inspection.HLintInspectionTool$$anon$1.call(HLintInspectionTool.scala:51)
	at intellij.haskell.inspection.HLintInspectionTool$$anon$1.call(HLintInspectionTool.scala:48)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.call(ApplicationImpl.java:337)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```
 * I've occasionally seen other things it gets other than just `["Main"]` - module names? 

### Workaround
Just continue and pretend it doesn't happen. Most / all things seem to work still.

**Comment by rikvdkleij** [comment]
This issue is solved in latest betas (I assume you are using beta12).
See
https://github.com/rikvdkleij/intellij-haskell#installing-latest-beta-of-the-plugin

I will publish soon a new version to the stable plugin repo channel.

**Comment by Sir4ur0n** [comment]
@rikvdkleij close this issue?

**Comment by rikvdkleij** [comment]
@Sir4ur0n Yes.
