### ISSUE TITLE
IntelliJ-Haskell throws IllegalStateException after update IDEA to 2018.3.1

### ISSUE THREAD

**Issue by stefanscheidt** [rikvdkleij/intellij-haskell#355]
I just updated IDEA to 2018.3.1 (details see below).
After Restart the IntelliJ-Haskell plugin throws the following exception, without opening a Stack project.

Stacktracke:

```
java.lang.IllegalStateException: TextAttributeKey(name:'CABAL_COLON', fallbackAttributeKey:'DEFAULT_BRACES')  was already registered with the other fallback attribute key: DEFAULT_OPERATION_SIGN
	at com.intellij.openapi.editor.colors.TextAttributesKey.mergeKeys(TextAttributesKey.java:214)
	at com.intellij.openapi.editor.colors.TextAttributesKey.lambda$getOrCreate$4(TextAttributesKey.java:200)
	at java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1877)
	at com.intellij.openapi.editor.colors.TextAttributesKey.getOrCreate(TextAttributesKey.java:200)
	at com.intellij.openapi.editor.colors.TextAttributesKey.createTextAttributesKey(TextAttributesKey.java:187)
	at intellij.haskell.cabal.highlighting.CabalSyntaxHighlighter$.<init>(CabalSyntaxHighlighter.scala:15)
	at intellij.haskell.cabal.highlighting.CabalSyntaxHighlighter$.<clinit>(CabalSyntaxHighlighter.scala)
	at intellij.haskell.cabal.highlighting.CabalSyntaxHighlighter.KEY(CabalSyntaxHighlighter.scala)
	at intellij.haskell.cabal.highlighting.CabalColorSettingsPage.<clinit>(CabalColorSettingsPage.java:20)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.picocontainer.defaults.InstantiatingComponentAdapter.newInstance(InstantiatingComponentAdapter.java:193)
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.doGetComponentInstance(CachingConstructorInjectionComponentAdapter.java:85)
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.instantiateGuarded(CachingConstructorInjectionComponentAdapter.java:62)
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.getComponentInstance(CachingConstructorInjectionComponentAdapter.java:45)
	at com.intellij.openapi.extensions.impl.ExtensionComponentAdapter.getComponentInstance(ExtensionComponentAdapter.java:72)
	at com.intellij.openapi.extensions.impl.ExtensionComponentAdapter.getExtension(ExtensionComponentAdapter.java:113)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.processAdapters(ExtensionPointImpl.java:252)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.getExtensionList(ExtensionPointImpl.java:179)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.getExtensions(ExtensionPointImpl.java:197)
	at com.intellij.openapi.extensions.ExtensionPointName.getExtensions(ExtensionPointName.java:27)
	at com.intellij.openapi.options.colors.pages.ColorSettingsPagesImpl.getRegisteredPages(ColorSettingsPagesImpl.java:28)
	at com.intellij.application.options.colors.ColorAndFontOptions.initPluggedDescriptions(ColorAndFontOptions.java:524)
	at com.intellij.application.options.colors.ColorAndFontOptions.initScheme(ColorAndFontOptions.java:516)
	at com.intellij.application.options.colors.ColorAndFontOptions.initAll(ColorAndFontOptions.java:506)
	at com.intellij.application.options.colors.ColorAndFontOptions.buildConfigurables(ColorAndFontOptions.java:370)
	at com.intellij.openapi.options.SearchableConfigurable$Parent$Abstract.getConfigurables(SearchableConfigurable.java:95)
	at com.intellij.openapi.options.ex.ConfigurableWrapper$CompositeWrapper.getConfigurables(ConfigurableWrapper.java:254)
	at com.intellij.ide.actions.ShowSettingsUtilImpl.collect(ShowSettingsUtilImpl.java:76)
	at com.intellij.ide.actions.ShowSettingsUtilImpl.collect(ShowSettingsUtilImpl.java:76)
	at com.intellij.ide.actions.ShowSettingsUtilImpl.getConfigurables(ShowSettingsUtilImpl.java:67)
	at com.intellij.ide.util.gotoByName.GotoActionModel.lambda$new$0(GotoActionModel.java:90)
	at com.intellij.openapi.util.VolatileNotNullLazyValue$1.compute(VolatileNotNullLazyValue.java:54)
	at com.intellij.openapi.util.VolatileNotNullLazyValue.getValue(VolatileNotNullLazyValue.java:34)
	at com.intellij.ide.util.gotoByName.GotoActionModel.getConfigurablesNames(GotoActionModel.java:331)
	at com.intellij.ide.util.gotoByName.GotoActionItemProvider.processOptions(GotoActionItemProvider.java:120)
	at com.intellij.ide.util.gotoByName.GotoActionItemProvider.filterElements(GotoActionItemProvider.java:76)
	at com.intellij.ide.actions.searcheverywhere.ActionSearchEverywhereContributor.fetchElements(ActionSearchEverywhereContributor.java:74)
	at com.intellij.ide.actions.searcheverywhere.MultithreadSearcher$ContributorSearchTask.run(MultithreadSearcher.java:182)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:229)
	at com.intellij.util.ConcurrencyUtil$3.run(ConcurrencyUtil.java:215)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:314)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

IDEA Version:

IntelliJ IDEA 2018.3.1 (Ultimate Edition)
Build #IU-183.4588.61, built on December 4, 2018
Licensed to REWE Digital GmbH / Stefan Scheidt
Subscription is active until September 2, 2019
JRE: 1.8.0_152-release-1343-b16 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.13.6

**Comment by rikvdkleij** [comment]
Which version of the plugin are you using?

**Comment by rikvdkleij** [comment]
Otherwise (re)install beta36.

**Comment by stefanscheidt** [comment]
I do use v1.0.0-beta12 and try to install a newer version.

**Comment by stefanscheidt** [comment]
Exception not thrown after update to beta36.

**Comment by AllanWang** [comment]
Are there plans to update the [plugin listing](https://plugins.jetbrains.com/plugin/8258-intellij-haskell)? It's still at beta12

**Comment by rikvdkleij** [comment]
@AllanWang Yes, you're right.
Still have some issues to solve before releasing version 1, publish to stable repo channel and update github readme.
