### ISSUE TITLE
Error handling on file path parsing

### ISSUE THREAD

**Issue by ice1000** [rikvdkleij/intellij-haskell#365]
```
java.nio.file.InvalidPathException: Illegal char <:> at index 25: /RegExp Fragment (Core.hs:2969).regexp
	at sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
	at sun.nio.fs.WindowsPath.parse(WindowsPath.java:94)
	at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:255)
	at java.nio.file.Paths.get(Paths.java:84)
	at intellij.haskell.util.HaskellProjectUtil$.$anonfun$isModuleFile$1(HaskellProjectUtil.scala:106)
	at intellij.haskell.util.HaskellProjectUtil$.$anonfun$isModuleFile$1$adapted(HaskellProjectUtil.scala:106)
	at scala.collection.IndexedSeqOptimized.prefixLengthImpl(IndexedSeqOptimized.scala:37)
	at scala.collection.IndexedSeqOptimized.exists(IndexedSeqOptimized.scala:45)
	at scala.collection.IndexedSeqOptimized.exists$(IndexedSeqOptimized.scala:45)
	at scala.collection.mutable.WrappedArray.exists(WrappedArray.scala:37)
	at intellij.haskell.util.HaskellProjectUtil$.isModuleFile(HaskellProjectUtil.scala:106)
	at intellij.haskell.util.HaskellProjectUtil$.getHaskellProjectFileType(HaskellProjectUtil.scala:86)
	at intellij.haskell.util.HaskellProjectUtil$.isSourceFile(HaskellProjectUtil.scala:94)
	at intellij.haskell.notification.SetupHaskellSdkNotificationProvider.createNotificationPanel(SetupHaskellSdkNotificationProvider.scala:30)
	at intellij.haskell.notification.SetupHaskellSdkNotificationProvider.createNotificationPanel(SetupHaskellSdkNotificationProvider.scala:19)
	at com.intellij.ui.EditorNotificationsImpl$3.performInReadAction(EditorNotificationsImpl.java:136)
	at com.intellij.openapi.progress.util.ReadTask.lambda$runBackgroundProcess$0(ReadTask.java:66)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:977)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:57)
	at com.intellij.openapi.progress.util.ReadTask.runBackgroundProcess(ReadTask.java:66)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runUnderProgress$4(ProgressIndicatorUtils.java:227)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$3(CoreProgressManager.java:180)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:164)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:582)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:532)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:87)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:151)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:180)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runUnderProgress(ProgressIndicatorUtils.java:225)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.access$100(ProgressIndicatorUtils.java:33)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils$4.run(ProgressIndicatorUtils.java:176)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:227)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$100(BoundedTaskExecutor.java:26)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2$1.run(BoundedTaskExecutor.java:200)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:229)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:194)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by rikvdkleij** [comment]
Should be fixed.

**Comment by rikvdkleij** [comment]
Btw, weird that this issue does not occur on more places because this construction of `Path.get` is used more.

**Comment by ice1000** [comment]
Nice.

**Comment by ice1000** [comment]
> Btw, weird that this issue does not occur on more places because this construction of Path.get is used more.

This is caused by language injection. Without language injection this don't happen.
