### ISSUE TITLE
Cannot download cabal config file for stack resolver lts-13.2

### ISSUE THREAD

**Issue by mouse07410** [rikvdkleij/intellij-haskell#377]
The error message is
```
13:26	Can not download cabal config file for stack resolver lts-13.2, please check your network environment.
```
I might've believed it if everything else network-related (including updates to this plugin) wasn't working fine. 

But this system is behind a corporate firewall and requires Web proxy. Perhaps something here is trying to ignore the proxy settings and gets blocked by the firewall? Or maybe only `lts-12` is configured, so when the plugin sees a project that asks for `lts-13.2` it goes belly-up?

Here's the detailed error:
```
java.util.concurrent.CompletionException: java.io.FileNotFoundException: /Users/ur20980/Library/Caches/com.github.rikvdkleij.intellij-haskell/p-test/cabal.config (No such file or directory)
	at com.github.benmanes.caffeine.cache.UnboundedLocalCache$UnboundedLocalLoadingCache.lambda$new$0(UnboundedLocalCache.java:936)
	at com.github.benmanes.caffeine.cache.UnboundedLocalCache.lambda$computeIfAbsent$2(UnboundedLocalCache.java:236)
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660)
	at com.github.benmanes.caffeine.cache.UnboundedLocalCache.computeIfAbsent(UnboundedLocalCache.java:232)
	at com.github.benmanes.caffeine.cache.LocalCache.computeIfAbsent(LocalCache.java:112)
	at com.github.benmanes.caffeine.cache.LocalLoadingCache.get(LocalLoadingCache.java:67)
	at com.github.blemale.scaffeine.LoadingCache.get(LoadingCache.scala:30)
	at intellij.haskell.external.component.GlobalProjectInfoComponent$.findGlobalProjectInfo(GlobalProjectInfoComponent.scala:36)
	at intellij.haskell.external.component.HaskellComponentsManager$.getGhcVersion(HaskellComponentsManager.scala:136)
	at intellij.haskell.util.HaskellProjectUtil$.setNoDiagnosticsShowCaretFlag(HaskellProjectUtil.scala:39)
	at intellij.haskell.external.execution.StackCommandLine$.ghcOptions(StackCommandLine.scala:90)
	at intellij.haskell.external.execution.StackCommandLine$.buildProjectInMessageView(StackCommandLine.scala:98)
	at intellij.haskell.external.component.StackProjectManager$$anon$2.run(StackProjectManager.scala:150)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:727)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:164)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:582)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:532)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:87)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:151)
	at com.intellij.openapi.progress.impl.CoreProgressManager$4.run(CoreProgressManager.java:403)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:314)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.FileNotFoundException: /Users/ur20980/Library/Caches/com.github.rikvdkleij.intellij-haskell/p-test/cabal.config (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at scala.io.Source$.fromFile(Source.scala:94)
	at scala.io.Source$.fromFile(Source.scala:79)
	at scala.io.Source$.fromFile(Source.scala:57)
	at intellij.haskell.external.component.CabalConfigComponent$.parseCabalConfigFile(CabalConfigComponent.scala:71)
	at intellij.haskell.external.component.CabalConfigComponent$.downloadAndParseCabalConfigFile(CabalConfigComponent.scala:56)
	at intellij.haskell.external.component.CabalConfigComponent$.$anonfun$getAvailablePackageNames$1(CabalConfigComponent.scala:31)
	at scala.Option.map(Option.scala:163)
	at intellij.haskell.external.component.CabalConfigComponent$.getAvailablePackageNames(CabalConfigComponent.scala:28)
	at intellij.haskell.external.component.GlobalProjectInfoComponent$.getAvailableStackagesPackages(GlobalProjectInfoComponent.scala:54)
	at intellij.haskell.external.component.GlobalProjectInfoComponent$.$anonfun$createGlobalProjectInfo$4(GlobalProjectInfoComponent.scala:73)
	at scala.Option.map(Option.scala:163)
	at intellij.haskell.external.component.GlobalProjectInfoComponent$.$anonfun$createGlobalProjectInfo$3(GlobalProjectInfoComponent.scala:68)
	at scala.Option.flatMap(Option.scala:188)
	at intellij.haskell.external.component.GlobalProjectInfoComponent$.$anonfun$createGlobalProjectInfo$2(GlobalProjectInfoComponent.scala:67)
	at scala.Option.flatMap(Option.scala:188)
	at intellij.haskell.external.component.GlobalProjectInfoComponent$.createGlobalProjectInfo(GlobalProjectInfoComponent.scala:65)
	at intellij.haskell.external.component.GlobalProjectInfoComponent$.$anonfun$Cache$1(GlobalProjectInfoComponent.scala:32)
	at com.github.blemale.scaffeine.CacheLoaderAdapter.load(CacheLoaderAdapter.java:22)
	at com.github.benmanes.caffeine.cache.UnboundedLocalCache$UnboundedLocalLoadingCache.lambda$new$0(UnboundedLocalCache.java:929)
	... 25 more
```

**Comment by rikvdkleij** [comment]
It should be the cabal.config of the Stack resolver of your project.

**Comment by mouse07410** [comment]
> It should be the `cabal.config` of the Stack resolver of your project

Yes, but I don't control Stack resolvers. When I created a new project, Stack chose `LTS-13.2` (now it's picking `LTS-13.3`). 

Plain Stack (i.e., without your plugin) seems to have no problem dealing with this project:
```
$ ls
ChangeLog.md		README.md		app			p-test.cabal		src			test
LICENSE			Setup.hs		ghc-paths-build.txt	package.yaml		stack.yaml
$ fgrep resolver stack.yaml
# A snapshot resolver dictates the compiler version and the set of packages
# resolver: lts-3.5
# resolver: nightly-2015-09-21
# resolver: ghc-7.10.2
# resolver: ./custom-snapshot.yaml
# resolver: https://example.com/snapshots/2018-01-01.yaml
resolver: lts-13.2
# Dependency packages to be pulled from upstream that are not in the resolver
$ stack build
$ stack run
Invoving a function from imported Lib:
someFunc()
$ 
```

So, it looks like something unnecessary that the plugin insists on doing.

**Comment by rikvdkleij** [comment]
Plugin downloads `cabal.config` to support package name completion in cabal file.

**Comment by mouse07410** [comment]
> Plugin downloads cabal.config to support package name completion in cabal file

Your plugin relies on Stack only, as you said before. Plain Stack (as I showed above) has no problem dealing with dependencies and such.

What can we do to remedy this situation? Especially since neither I nor you control what files are included in the resolver.

**Comment by rikvdkleij** [comment]
I do not see the problem.

**Comment by mouse07410** [comment]
> I do not see the problem.

The problem is that the plugin tries to build `intero` and fails upon `ghc-paths` failure. *I* see it - or rather, experience it.

I'd like to experiment, and for that I'd like to be able to add parameters to *all* the `stack` invocations by the plugin.

> Okay, I can prevent the exception being thrown

That would probably help - I can't tell. But if `ghc-paths` failed to install - that means `intero` will fail to install. The workaround I was thinking of was telling the plugin to use another copy of `intero` - is it possible?

**Comment by rikvdkleij** [comment]
There is no connection between the `cabal.config` and the working of stack, intero, and so on.

Like I said, it's only used to support package name completion in cabal file. But I see that the exception destroys the building of the `GlobalProjectInfo`.
