### ISSUE TITLE
Fatal IDE Error on IDEA 2019.1

### ISSUE THREAD

**Issue by enolive** [rikvdkleij/intellij-haskell#419]
After upgrading to 2019.1, I noticed a reoccuring error reported by IDEA. The dialog says that the plugin is at fault, so I thought that I should report it here. As far as I can see, besides from the confusing report, there are no side effects in the IDE. 

```
java.lang.RuntimeException: java.lang.RuntimeException: Not implemented because no session id is available and need current file to clear only old messages of that file.
	at org.jetbrains.jps.api.BasicFuture.cancel(BasicFuture.java:54)
	at com.intellij.compiler.server.BuildManager$DelegateFuture.a(BuildManager.java:1902)
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
	at com.intellij.compiler.server.BuildManager$DelegateFuture.cancel(BuildManager.java:1902)
	at com.intellij.compiler.server.BuildManager.cancelAutoMakeTasks(BuildManager.java:630)
	at com.intellij.compiler.server.BuildManager$ProjectWatcher$2.processStarting(BuildManager.java:1575)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.util.messages.impl.MessageBusConnectionImpl.deliverMessage(MessageBusConnectionImpl.java:114)
	at com.intellij.util.messages.impl.MessageBusImpl.doPumpMessages(MessageBusImpl.java:393)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpWaitingBuses(MessageBusImpl.java:354)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:343)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:327)
	at com.intellij.util.messages.impl.MessageBusImpl.sendMessage(MessageBusImpl.java:320)
	at com.intellij.util.messages.impl.MessageBusImpl.access$100(MessageBusImpl.java:29)
	at com.intellij.util.messages.impl.MessageBusImpl$1.invoke(MessageBusImpl.java:192)
	at com.sun.proxy.$Proxy195.processStarting(Unknown Source)
	at com.intellij.execution.impl.ExecutionManagerKtImpl$startRunProfile$startRunnable$1.run(ExecutionManagerKtImpl.kt:52)
	at com.intellij.openapi.application.TransactionGuardImpl.runSyncTransaction(TransactionGuardImpl.java:88)
	at com.intellij.openapi.application.TransactionGuardImpl.lambda$pollQueueLater$0(TransactionGuardImpl.java:74)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:435)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:419)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:403)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:741)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:690)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:385)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.RuntimeException: Not implemented because no session id is available and need current file to clear only old messages of that file.
	at intellij.haskell.editor.HaskellProblemsView.clearOldMessages(HaskellProblemsView.scala:59)
	at com.intellij.compiler.server.AutoMakeMessageHandler.sessionTerminated(AutoMakeMessageHandler.java:182)
	at com.intellij.compiler.server.DelegatingMessageHandler.sessionTerminated(DelegatingMessageHandler.java:33)
	at com.intellij.compiler.server.BuildManager$NotifyingMessageHandler.sessionTerminated(BuildManager.java:1512)
	at com.intellij.compiler.server.DelegatingMessageHandler.sessionTerminated(DelegatingMessageHandler.java:33)
	at com.intellij.compiler.server.DelegatingMessageHandler.sessionTerminated(DelegatingMessageHandler.java:33)
	at com.intellij.compiler.server.BuildMessageDispatcher$1.sessionTerminated(BuildMessageDispatcher.java:44)
	at com.intellij.compiler.server.BuildManager.b(BuildManager.java:913)
	at com.intellij.compiler.server.BuildManager.access$2300(BuildManager.java:114)
	at com.intellij.compiler.server.BuildManager$CancelBuildSessionAction.cancel(BuildManager.java:1962)
	at org.jetbrains.jps.api.RequestFuture.performCancel(RequestFuture.java:54)
	at org.jetbrains.jps.api.BasicFuture.cancel(BasicFuture.java:51)
	... 42 more
```

![image](https://user-images.githubusercontent.com/20992515/57015169-9d416d80-6c13-11e9-9f6b-177ecbd4023e.png)

**Comment by rikvdkleij** [comment]
Thanks for reporting!

**Comment by rikvdkleij** [comment]
I wonder how I can reproduce this issue because I do not expect that the method is called.

**Comment by rikvdkleij** [comment]
@enolive Do you still have this issue?

**Comment by enolive** [comment]
Yeah. Happy to know there is a workaround for this. Will test it with the next version of the plugin!

**Comment by rikvdkleij** [comment]
Thanks!

Should be fixed in beta47.

**Comment by enolive** [comment]
so far, I did not encounter any additional IDE error. using 0.48 But for non-haskell projects, the haskell problems tool window is filled with clutter from other build tools such as gradle. Is this an intended behaviour?

I think I forgot to mention that the issue seems only to occur in non-haskell projects :scream: 

![grafik](https://user-images.githubusercontent.com/20992515/58986709-4b759f80-87de-11e9-8db5-0675fa8a2ddf.png)

**Comment by rikvdkleij** [comment]
No, it's not intended behavior.

I did not notice this problem because in non-Haskell project I can not see the Haskell Problems view. How can I reproduce your issue?

**Comment by enolive** [comment]
that's easy: 

1. create a Gradle Project
2. add a Java class
3. break the build by producing some compile errors (for example, with my test case :wink:)
4. rebuild the projects (Ctrl+F9)
5. open the haskell tool window and see the gradle output in there

```
public class BrokenShit {
  this does not compile
}
```

I assume that there are other ways to produce this error, but this is how I first realized it in a non-Haskell project (except with Groovy instead of Java).

**Comment by rikvdkleij** [comment]
Hopefully fixed in beta49 :smile:

**Comment by rikvdkleij** [comment]
@enolive Is it fixed?

**Comment by enolive** [comment]
@rikvdkleij yeah, it is! Thanks for your work!
