### ISSUE TITLE
java.lang.NoSuchMethodError using autocompletion

### ISSUE THREAD

**Issue by maciekc** [rikvdkleij/intellij-haskell#423]
Intellij 2018.3
Intellij-Haskell 1.0.0-beta46
Windows 7

When I tried to use auto-completion for function name (CTRL + Space) I got the following stack trace exception:
java.lang.NoSuchMethodError: com.intellij.openapi.util.text.StringUtil.unescapeXmlEntities(Ljava/lang/String;)Ljava/lang/String;
	at intellij.haskell.editor.HaskellCompletionContributor.$anonfun$createLocalLookupElement$2(HaskellCompletionContributor.scala:478)
	at scala.util.Either.map(Either.scala:353)
	at intellij.haskell.editor.HaskellCompletionContributor.createLocalLookupElement(HaskellCompletionContributor.scala:478)
	at intellij.haskell.editor.HaskellCompletionContributor.$anonfun$findTopLeveLookupElements$7(HaskellCompletionContributor.scala:445)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:237)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at scala.collection.TraversableLike.map(TraversableLike.scala:237)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:230)
	at scala.collection.immutable.List.map(List.scala:298)
	at intellij.haskell.editor.HaskellCompletionContributor.findTopLeveLookupElements(HaskellCompletionContributor.scala:445)
	at intellij.haskell.editor.HaskellCompletionContributor.intellij$haskell$editor$HaskellCompletionContributor$$getAvailableLookupElements(HaskellCompletionContributor.scala:425)
	at intellij.haskell.editor.HaskellCompletionContributor$$anon$1.$anonfun$addCompletions$30(HaskellCompletionContributor.scala:208)
	at intellij.haskell.editor.HaskellCompletionContributor$$anon$1.$anonfun$addCompletions$30$adapted(HaskellCompletionContributor.scala:208)
	at scala.Option.foreach(Option.scala:274)

**Comment by rikvdkleij** [comment]
Can you try IntelliJ 2019.1?

**Comment by maciekc** [comment]
It works with IntelliJ 2019.1.
Problem resolved
