### ISSUE TITLE
Plugin crashes on welcome page, when I click `Create New Project`

### ISSUE THREAD

**Issue by faucct** [rikvdkleij/intellij-haskell#43]
Here are the logs:
```
2016-05-27 17:44:55,371 [  52664]  ERROR - llij.ide.plugins.PluginManager - org.jetbrains.haskell.module.HaskellModuleType cannot be cast to intellij.haskell.module.HaskellModuleType 
java.lang.ClassCastException: org.jetbrains.haskell.module.HaskellModuleType cannot be cast to intellij.haskell.module.HaskellModuleType
	at intellij.haskell.module.HaskellModuleType$.getInstance(HaskellModuleType.scala:57)
	at intellij.haskell.module.HaskellModuleBuilder.getModuleType(HaskellModuleBuilder.scala:32)
	at com.intellij.ide.util.projectWizard.ModuleBuilder.getModuleTypeName(ModuleBuilder.java:384)
	at com.intellij.ide.util.projectWizard.ModuleBuilder.getPresentableName(ModuleBuilder.java:380)
	at com.intellij.ide.util.newProjectWizard.TemplatesGroup.<init>(TemplatesGroup.java:61)
	at com.intellij.ide.projectWizard.ProjectTypeStep.fillTemplatesMap(ProjectTypeStep.java:296)
	at com.intellij.ide.projectWizard.ProjectTypeStep.<init>(ProjectTypeStep.java:134)
	at com.intellij.ide.projectWizard.NewProjectWizard.init(NewProjectWizard.java:50)
	at com.intellij.ide.projectWizard.NewProjectWizard.<init>(NewProjectWizard.java:39)
	at com.intellij.ide.actions.NewProjectAction.actionPerformed(NewProjectAction.java:30)
	at com.intellij.ui.components.labels.ActionLink$1.linkSelected(ActionLink.java:64)
	at com.intellij.ui.components.labels.LinkLabel.doClick(LinkLabel.java:116)
	at com.intellij.ui.components.labels.ActionLink.doClick(ActionLink.java:77)
	at com.intellij.ui.components.labels.LinkLabel$MyMouseHandler.mouseReleased(LinkLabel.java:287)
	at java.awt.Component.processMouseEvent(Component.java:6533)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6298)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:857)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:654)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:386)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
2016-05-27 17:44:55,372 [  52665]  ERROR - llij.ide.plugins.PluginManager - IntelliJ IDEA 2016.1.2  Build #IC-145.972.3 
2016-05-27 17:44:55,372 [  52665]  ERROR - llij.ide.plugins.PluginManager - JDK: 1.8.0_76-release 
2016-05-27 17:44:55,372 [  52665]  ERROR - llij.ide.plugins.PluginManager - VM: OpenJDK 64-Bit Server VM 
2016-05-27 17:44:55,372 [  52665]  ERROR - llij.ide.plugins.PluginManager - Vendor: JetBrains s.r.o 
2016-05-27 17:44:55,372 [  52665]  ERROR - llij.ide.plugins.PluginManager - OS: Mac OS X 
2016-05-27 17:44:55,372 [  52665]  ERROR - llij.ide.plugins.PluginManager - Last Action: $SelectAll 
 ```

**Comment by zjhmale** [comment]
>2016-05-27 17:44:55,372 [  52665]  ERROR - llij.ide.plugins.PluginManager - IntelliJ IDEA 2016.1.2  Build #IC-145.972.3 
2016-05-27 17:44:55,372 [  52665]  ERROR - llij.ide.plugins.PluginManager - JDK: 1.8.0_76-release 
2016-05-27 17:44:55,372 [  52665]  ERROR - llij.ide.plugins.PluginManager - VM: OpenJDK 64-Bit Server VM 
2016-05-27 17:44:55,372 [  52665]  ERROR - llij.ide.plugins.PluginManager - Vendor: JetBrains s.r.o 
2016-05-27 17:44:55,372 [  52665]  ERROR - llij.ide.plugins.PluginManager - OS: Mac OS X 

this is caused by the version of JRE i guess, you can try to run IDEA with [Apple's JDK6](https://support.apple.com/kb/DL1572).

**Comment by faucct** [comment]
It tells me that 1.8 is required for IDEA 2016.1. Should I try using apple's 1.8 or this IDEA version is not supported at all?

**Comment by faucct** [comment]
Installed the IDEA15, same issue when running it on JDK6

**Comment by zjhmale** [comment]
that's really wired, IDEA15 and Apple's JDK6 works for me.

**Comment by rikvdkleij** [comment]
Plugin is built with target bytecode 1.6

**Comment by faucct** [comment]
Logs from IDEA15:
```
2016-05-28 18:02:40,825 [3698320]  ERROR - llij.ide.plugins.PluginManager - org.jetbrains.haskell.module.HaskellModuleType cannot be cast to intellij.haskell.module.HaskellModuleType 
java.lang.ClassCastException: org.jetbrains.haskell.module.HaskellModuleType cannot be cast to intellij.haskell.module.HaskellModuleType
	at intellij.haskell.module.HaskellModuleType$.getInstance(HaskellModuleType.scala:57)
	at intellij.haskell.module.HaskellModuleBuilder.getModuleType(HaskellModuleBuilder.scala:32)
	at com.intellij.ide.util.projectWizard.ModuleBuilder.getModuleTypeName(ModuleBuilder.java:384)
	at com.intellij.ide.util.projectWizard.ModuleBuilder.getPresentableName(ModuleBuilder.java:380)
	at com.intellij.ide.util.newProjectWizard.TemplatesGroup.<init>(TemplatesGroup.java:61)
	at com.intellij.ide.projectWizard.ProjectTypeStep.fillTemplatesMap(ProjectTypeStep.java:298)
	at com.intellij.ide.projectWizard.ProjectTypeStep.<init>(ProjectTypeStep.java:136)
	at com.intellij.ide.projectWizard.NewProjectWizard.init(NewProjectWizard.java:50)
	at com.intellij.ide.projectWizard.NewProjectWizard.<init>(NewProjectWizard.java:39)
	at com.intellij.ide.actions.NewProjectAction.actionPerformed(NewProjectAction.java:30)
	at com.intellij.ui.components.labels.ActionLink$1.linkSelected(ActionLink.java:64)
	at com.intellij.ui.components.labels.LinkLabel.doClick(LinkLabel.java:106)
	at com.intellij.ui.components.labels.ActionLink.doClick(ActionLink.java:77)
	at com.intellij.ui.components.labels.LinkLabel$MyMouseHandler.mouseReleased(LinkLabel.java:277)
	at java.awt.Component.processMouseEvent(Component.java:6414)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3275)
	at java.awt.Component.processEvent(Component.java:6179)
	at java.awt.Container.processEvent(Container.java:2084)
	at java.awt.Component.dispatchEventImpl(Component.java:4776)
	at java.awt.Container.dispatchEventImpl(Container.java:2142)
	at java.awt.Component.dispatchEvent(Component.java:4604)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4618)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4279)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4209)
	at java.awt.Container.dispatchEventImpl(Container.java:2128)
	at java.awt.Window.dispatchEventImpl(Window.java:2492)
	at java.awt.Component.dispatchEvent(Component.java:4604)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:717)
	at java.awt.EventQueue.access$400(EventQueue.java:82)
	at java.awt.EventQueue$2.run(EventQueue.java:676)
	at java.awt.EventQueue$2.run(EventQueue.java:674)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:86)
	at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:690)
	at java.awt.EventQueue$3.run(EventQueue.java:688)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:86)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:687)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:866)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:650)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:381)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:296)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:211)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:196)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:188)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)
2016-05-28 18:02:40,828 [3698323]  ERROR - llij.ide.plugins.PluginManager - IntelliJ IDEA 15.0.6  Build #IC-143.2370.31 
2016-05-28 18:02:40,828 [3698323]  ERROR - llij.ide.plugins.PluginManager - JDK: 1.6.0_65 
2016-05-28 18:02:40,828 [3698323]  ERROR - llij.ide.plugins.PluginManager - VM: Java HotSpot(TM) 64-Bit Server VM 
2016-05-28 18:02:40,828 [3698323]  ERROR - llij.ide.plugins.PluginManager - Vendor: Apple Inc. 
2016-05-28 18:02:40,828 [3698323]  ERROR - llij.ide.plugins.PluginManager - OS: Mac OS X 
```

**Comment by faucct** [comment]
IDEA14 the same

**Comment by faucct** [comment]
Haskforce plugin crashes with the exact same error

**Comment by zjhmale** [comment]
>Haskforce plugin crashes with the exact same error

😂  btw, which version of Mac OS X do you use?

**Comment by faucct** [comment]
The latest El Capitan, 10.11.5

**Comment by faucct** [comment]
Okay, the problem was that I have had a jetbrains haskell plugin enabled, they conflict. You should probably have that written somewhere in readme file.

**Comment by chris-martin** [comment]
I just got this because I had Haskforce enabled. It'd be nice if it could give a better error somehow?

**Comment by zjhmale** [comment]
@chris-martin IIRC, there is no proper way to give a kindly error message to point out this plugin confliction, just make sure you have only one Haskell plugin enabled with your Intellij :sweat_smile: . If there is an official API that we can query already installed plugins and get each languagID, it can lead a door to fix this.

@rikvdkleij maybe this can be add to README or something like COMMON QUESTIONS to avoid more misunderstanding?

**Comment by rikvdkleij** [comment]
There is already comment in README. I will make it more clear.

**Comment by chris-martin** [comment]
Oh it's already clear in the readme. I'm just not in the habit of looking for a readme for IntelliJ plugins because they don't usually require any setup explanation :P
