### ISSUE TITLE
com.intellij.psi.PsiInvalidElementAccessException onContentReload (beta48)

### ISSUE THREAD

**Issue by aryairani** [rikvdkleij/intellij-haskell#431]
Not sure how to reproduce this, but thought you'd want to know.

I got it after doing a git pull updating from unisonweb/unison@71733380 to unisonweb/unison@c8afa50f while the project was open.

```
com.intellij.psi.PsiInvalidElementAccessException: Element: class intellij.haskell.psi.impl.HaskellConidImpl #Haskell 
invalidated at: see attachment
	at com.intellij.psi.impl.source.SubstrateRef$1.getNode(SubstrateRef.java:65)
	at com.intellij.extapi.psi.StubBasedPsiElementBase.getNode(StubBasedPsiElementBase.java:148)
	at com.intellij.extapi.psi.ASTDelegatePsiElement.getText(ASTDelegatePsiElement.java:146)
	at intellij.haskell.psi.impl.HaskellPsiImplUtil$.getName(HaskellPsiImplUtil.scala:140)
	at intellij.haskell.psi.impl.HaskellPsiImplUtil.getName(HaskellPsiImplUtil.scala)
	at intellij.haskell.psi.impl.HaskellConidImpl.getName(HaskellConidImpl.java:38)
	at intellij.haskell.external.component.DefinitionLocationComponent$.$anonfun$checkValidName$2(DefinitionLocationComponent.scala:107)
	at intellij.haskell.util.ScalaUtil$$anon$2.compute(ScalaUtil.scala:41)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:960)
	at intellij.haskell.util.ApplicationUtil$.runReadAction(ApplicationUtil.scala:49)
	at intellij.haskell.external.component.DefinitionLocationComponent$.checkValidName(DefinitionLocationComponent.scala:107)
	at intellij.haskell.external.component.DefinitionLocationComponent$.$anonfun$invalidate$1(DefinitionLocationComponent.scala:83)
	at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:244)
	at scala.collection.Iterator.foreach(Iterator.scala:941)
	at scala.collection.Iterator.foreach$(Iterator.scala:941)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1429)
	at scala.collection.IterableLike.foreach(IterableLike.scala:74)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
	at scala.collection.TraversableLike.flatMap(TraversableLike.scala:244)
	at scala.collection.TraversableLike.flatMap$(TraversableLike.scala:241)
	at scala.collection.AbstractTraversable.flatMap(Traversable.scala:108)
	at intellij.haskell.external.component.DefinitionLocationComponent$.invalidate(DefinitionLocationComponent.scala:80)
	at intellij.haskell.external.component.LoadComponent$.$anonfun$load$2(LoadComponent.scala:59)
	at intellij.haskell.util.ScalaUtil$$anon$1.run(ScalaUtil.scala:36)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:311)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by rikvdkleij** [comment]
Thanks for reporting! Changed some code to prevent this kind of errors.

**Comment by aryairani** [comment]
Thanks.  Should I close the issue?

**Comment by rikvdkleij** [comment]
Should be fixed in  beta49, https://github.com/rikvdkleij/intellij-haskell/releases/tag/v1.0.0-beta49

> Thanks. Should I close the issue?

Yep, you can always reopen it if this issue still occurs.
