### ISSUE TITLE
Java Exceptions thrown in Windows 10

### ISSUE THREAD

**Issue by michaelpeternell** [rikvdkleij/intellij-haskell#435]
first exception:

    java.lang.RuntimeException: Could not create directory `C:\Users\michael\AppData\Local\rikvdkleij\intellij-haskell\cache`
      at intellij.haskell.util.HaskellFileUtil$.createDirectoryIfNotExists(HaskellFileUtil.scala:265)
      at intellij.haskell.GlobalInfo$.getIntelliJHaskellDirectory(GlobalInfo.scala:24)
      at intellij.haskell.GlobalInfo$.getLibrarySourcesPath(GlobalInfo.scala:30)
      at intellij.haskell.util.HaskellProjectUtil$.getProjectLibrarySourcesDirectory(HaskellProjectUtil.scala:77)
      at intellij.haskell.util.HaskellProjectUtil$.isLibraryFile(HaskellProjectUtil.scala:72)
      at intellij.haskell.external.component.DefinitionLocationComponent$.findDefinitionLocationResult(DefinitionLocationComponent.scala:116)
      at intellij.haskell.external.component.DefinitionLocationComponent$.findDefinitionLocation(DefinitionLocationComponent.scala:55)
      at intellij.haskell.external.component.HaskellComponentsManager$.findDefinitionLocation(HaskellComponentsManager.scala:61)
      at intellij.haskell.navigation.HaskellReference.resolveReferenceByDefinitionLocation(HaskellReference.scala:169)
      at intellij.haskell.navigation.HaskellReference.resolveReference(HaskellReference.scala:161)
      at intellij.haskell.navigation.HaskellReference.findImportedIdentifierDeclaration(HaskellReference.scala:66)
      at intellij.haskell.navigation.HaskellReference.multiResolve(HaskellReference.scala:105)
      at com.intellij.psi.PsiPolyVariantReferenceBase.resolve(PsiPolyVariantReferenceBase.java:47)
      at com.intellij.codeInsight.intention.AddAnnotationPsiFix.getContainer(AddAnnotationPsiFix.java:73)
      at com.intellij.codeInspection.dataFlow.EditContractIntention.getTargetMethod(EditContractIntention.java:46)
      at com.intellij.codeInspection.dataFlow.EditContractIntention.isAvailable(EditContractIntention.java:56)
      at com.intellij.codeInsight.intention.impl.ShowIntentionActionsHandler.availableFor(ShowIntentionActionsHandler.java:127)
      at com.intellij.codeInsight.daemon.impl.ShowIntentionsPass.lambda$getActionsToShow$1(ShowIntentionsPass.java:284)
      at com.intellij.codeInsight.intention.impl.ShowIntentionActionsHandler.chooseBetweenHostAndInjected(ShowIntentionActionsHandler.java:152)
      at com.intellij.codeInsight.daemon.impl.ShowIntentionsPass.getActionsToShow(ShowIntentionsPass.java:282)
      at com.intellij.codeInsight.daemon.impl.ShowIntentionsPass.getActionsToShow(ShowIntentionsPass.java:254)
      at com.intellij.codeInsight.daemon.impl.ShowIntentionsPass.doCollectInformation(ShowIntentionsPass.java:220)
      at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:69)
      at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$null$1(PassExecutorService.java:430)
      at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1166)
      at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:423)
      at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:586)
      at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:532)
      at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:86)
      at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:422)
      at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:398)
      at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:164)
      at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:218)
      at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:396)
      at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:174)
      at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
      at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
      at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
      at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

second exception:

    java.lang.NullPointerException
      at com.intellij.application.options.CodeStyleAbstractPanel.installPreviewPanel(CodeStyleAbstractPanel.java:435)
      at com.intellij.application.options.TabbedLanguageCodeStylePanel$MyIndentOptionsWrapper.<init>(TabbedLanguageCodeStylePanel.java:513)
      at com.intellij.application.options.TabbedLanguageCodeStylePanel.addIndentOptionsTab(TabbedLanguageCodeStylePanel.java:88)
      at intellij.haskell.editor.formatter.settings.HaskellCodeStyleConfigurable$HaskellCodeStyleMainPanel.initTabs(HaskellCodeStyleConfigurable.scala:36)
      at com.intellij.application.options.TabbedLanguageCodeStylePanel.ensureTabs(TabbedLanguageCodeStylePanel.java:121)
      at com.intellij.application.options.TabbedLanguageCodeStylePanel.getPreviewText(TabbedLanguageCodeStylePanel.java:198)
      at com.intellij.application.options.CodeStyleAbstractPanel.createEditor(CodeStyleAbstractPanel.java:137)
      at com.intellij.application.options.CodeStyleAbstractPanel.<init>(CodeStyleAbstractPanel.java:96)
      at com.intellij.application.options.TabbedLanguageCodeStylePanel.<init>(TabbedLanguageCodeStylePanel.java:54)
      at intellij.haskell.editor.formatter.settings.HaskellCodeStyleConfigurable$HaskellCodeStyleMainPanel.<init>(HaskellCodeStyleConfigurable.scala:34)
      at intellij.haskell.editor.formatter.settings.HaskellCodeStyleConfigurable.createPanel(HaskellCodeStyleConfigurable.scala:27)
      at com.intellij.application.options.CodeStyleAbstractConfigurable.createComponent(CodeStyleAbstractConfigurable.java:34)
      at com.intellij.application.options.codeStyle.NewCodeStyleSettingsPanel.<init>(NewCodeStyleSettingsPanel.java:35)
      at com.intellij.ConfigurableFactory$createCodeStyleConfigurable$codeStyleConfigurableWrapper$1.createPanel(ConfigurableFactory.kt:46)
      at com.intellij.application.options.codeStyle.CodeStyleMainPanel.ensurePanel(CodeStyleMainPanel.java:236)
      at com.intellij.application.options.codeStyle.CodeStyleMainPanel.ensureCurrentPanel(CodeStyleMainPanel.java:221)
      at com.intellij.application.options.codeStyle.CodeStyleMainPanel.access$000(CodeStyleMainPanel.java:36)
      at com.intellij.application.options.codeStyle.CodeStyleMainPanel$2.beforeCurrentSettingsChanged(CodeStyleMainPanel.java:88)
      at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
      at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
      at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
      at java.lang.reflect.Method.invoke(Method.java:498)
      at com.intellij.util.EventDispatcher.dispatchVoidMethod(EventDispatcher.java:132)
      at com.intellij.util.EventDispatcher.access$000(EventDispatcher.java:26)
      at com.intellij.util.EventDispatcher$1.invoke(EventDispatcher.java:90)
      at com.sun.proxy.$Proxy137.beforeCurrentSettingsChanged(Unknown Source)
      at com.intellij.application.options.codeStyle.CodeStyleSchemesModel.fireBeforeCurrentSettingsChanged(CodeStyleSchemesModel.java:179)
      at com.intellij.application.options.CodeStyleAbstractPanel.somethingChanged(CodeStyleAbstractPanel.java:127)
      at com.intellij.application.options.CodeStyleAbstractPanel.lambda$new$0(CodeStyleAbstractPanel.java:101)
      at sun.reflect.GeneratedMethodAccessor536.invoke(Unknown Source)
      at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
      at java.lang.reflect.Method.invoke(Method.java:498)
      at com.intellij.util.EventDispatcher.dispatchVoidMethod(EventDispatcher.java:132)
      at com.intellij.util.EventDispatcher.access$000(EventDispatcher.java:26)
      at com.intellij.util.EventDispatcher$1.invoke(EventDispatcher.java:90)
      at com.sun.proxy.$Proxy141.stateChanged(Unknown Source)
      at com.intellij.ui.UserActivityWatcher.fireUIChanged(UserActivityWatcher.java:92)
      at com.intellij.ui.UserActivityWatcher$3.tableChanged(UserActivityWatcher.java:41)
      at javax.swing.table.AbstractTableModel.fireTableChanged(AbstractTableModel.java:296)
      at javax.swing.table.AbstractTableModel.fireTableDataChanged(AbstractTableModel.java:198)
      at com.intellij.ui.treeStructure.treetable.TreeTableModelAdapter.fireTableDataChanged(TreeTableModelAdapter.java:156)
      at com.intellij.ui.treeStructure.treetable.TreeTableModelAdapter.lambda$delayedFireTableDataChanged$0(TreeTableModelAdapter.java:148)
      at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:435)
      at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:419)
      at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:403)
      at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
      at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
      at java.awt.EventQueue.access$500(EventQueue.java:98)
      at java.awt.EventQueue$3.run(EventQueue.java:715)
      at java.awt.EventQueue$3.run(EventQueue.java:709)
      at java.security.AccessController.doPrivileged(Native Method)
      at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
      at java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
      at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:729)
      at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:678)
      at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:373)
      at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
      at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
      at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:109)
      at java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:190)
      at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:235)
      at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:233)
      at java.security.AccessController.doPrivileged(Native Method)
      at java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:233)
      at java.awt.Dialog.show(Dialog.java:1077)
      at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog.show(DialogWrapperPeerImpl.java:706)
      at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl.show(DialogWrapperPeerImpl.java:437)
      at com.intellij.openapi.ui.DialogWrapper.invokeShow(DialogWrapper.java:1682)
      at com.intellij.openapi.ui.DialogWrapper.show(DialogWrapper.java:1631)
      at com.intellij.openapi.options.newEditor.SettingsDialog.lambda$show$0(SettingsDialog.java:73)
      at com.intellij.openapi.application.TransactionGuardImpl.runSyncTransaction(TransactionGuardImpl.java:88)
      at com.intellij.openapi.application.TransactionGuardImpl.submitTransactionAndWait(TransactionGuardImpl.java:153)
      at com.intellij.openapi.options.newEditor.SettingsDialog.show(SettingsDialog.java:73)
      at com.intellij.ide.actions.ShowSettingsUtilImpl.showSettingsDialog(ShowSettingsUtilImpl.java:84)
      at com.intellij.ide.actions.ShowSettingsAction.perform(ShowSettingsAction.java:54)
      at com.intellij.ide.actions.ShowSettingsAction.actionPerformed(ShowSettingsAction.java:41)
      at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:261)
      at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:278)
      at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.lambda$actionPerformed$0(ActionMenuItem.java:292)
      at com.intellij.openapi.wm.impl.FocusManagerImpl.runOnOwnContext(FocusManagerImpl.java:283)
      at com.intellij.openapi.wm.impl.IdeFocusManagerImpl.runOnOwnContext(IdeFocusManagerImpl.java:107)
      at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.actionPerformed(ActionMenuItem.java:282)
      at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
      at com.intellij.openapi.actionSystem.impl.ActionMenuItem.lambda$fireActionPerformed$0(ActionMenuItem.java:111)
      at com.intellij.openapi.application.TransactionGuardImpl.runSyncTransaction(TransactionGuardImpl.java:88)
      at com.intellij.openapi.application.TransactionGuardImpl.lambda$submitTransaction$1(TransactionGuardImpl.java:111)
      at com.intellij.openapi.application.TransactionGuardImpl.submitTransaction(TransactionGuardImpl.java:120)
      at com.intellij.openapi.application.TransactionGuard.submitTransaction(TransactionGuard.java:121)
      at com.intellij.openapi.actionSystem.impl.ActionMenuItem.fireActionPerformed(ActionMenuItem.java:111)
      at com.intellij.ui.plaf.beg.BegMenuItemUI.doClick(BegMenuItemUI.java:524)
      at com.intellij.ui.plaf.beg.BegMenuItemUI.access$300(BegMenuItemUI.java:35)
      at com.intellij.ui.plaf.beg.BegMenuItemUI$MyMouseInputHandler.mouseReleased(BegMenuItemUI.java:546)
      at java.awt.Component.processMouseEvent(Component.java:6550)
      at javax.swing.JComponent.processMouseEvent(JComponent.java:3325)
      at java.awt.Component.processEvent(Component.java:6315)
      at java.awt.Container.processEvent(Container.java:2239)
      at java.awt.Component.dispatchEventImpl(Component.java:4899)
      at java.awt.Container.dispatchEventImpl(Container.java:2297)
      at java.awt.Component.dispatchEvent(Component.java:4721)
      at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
      at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4535)
      at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
      at java.awt.Container.dispatchEventImpl(Container.java:2283)
      at java.awt.Window.dispatchEventImpl(Window.java:2746)
      at java.awt.Component.dispatchEvent(Component.java:4721)
      at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:766)
      at java.awt.EventQueue.access$500(EventQueue.java:98)
      at java.awt.EventQueue$3.run(EventQueue.java:715)
      at java.awt.EventQueue$3.run(EventQueue.java:709)
      at java.security.AccessController.doPrivileged(Native Method)
      at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
      at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
      at java.awt.EventQueue$4.run(EventQueue.java:739)
      at java.awt.EventQueue$4.run(EventQueue.java:737)
      at java.security.AccessController.doPrivileged(Native Method)
      at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
      at java.awt.EventQueue.dispatchEvent(EventQueue.java:736)
      at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:729)
      at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:674)
      at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:373)
      at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
      at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
      at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
      at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
      at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
      at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

I think the second exception is related to the bug that I cannot change the tab width from 2 to 4 for Haskell files: Go to File -> Settings -> Editor -> Code Style -> Haskell. The main dialog area says "Loading..." and stays like this forever.

**Comment by rikvdkleij** [comment]
Can this issue be closed?

**Comment by rikvdkleij** [comment]
Please reopen if still an issue.
