### ISSUE TITLE
Could not create directory

### ISSUE THREAD

**Issue by breandan** [rikvdkleij/intellij-haskell#444]
Running IntelliJ-Haskell 1.1.0 Beta 51 on
```
IntelliJ IDEA 2019.1.3 (Ultimate Edition)
Build #IU-191.7479.19, built on May 27, 2019
Licensed to idear / Breandan Considine
Subscription is active until July 23, 2019
For non-commercial open source development only.
JRE: 1.8.0_202-release-1483-b58 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.15.0-52-generic
```

I encountered the following error:

```
java.lang.RuntimeException: Could not create directory `/home/breandan/.cache/intellij-haskell`
	at intellij.haskell.util.HaskellFileUtil$.createDirectoryIfNotExists(HaskellFileUtil.scala:265)
	at intellij.haskell.GlobalInfo$.getIntelliJHaskellDirectory(GlobalInfo.scala:24)
	at intellij.haskell.GlobalInfo$.getLibrarySourcesPath(GlobalInfo.scala:30)
	at intellij.haskell.util.HaskellProjectUtil$.getProjectLibrarySourcesDirectory(HaskellProjectUtil.scala:77)
	at intellij.haskell.util.HaskellProjectUtil$.isLibraryFile(HaskellProjectUtil.scala:72)
	at intellij.haskell.external.component.DefinitionLocationComponent$.findDefinitionLocationResult(DefinitionLocationComponent.scala:124)
	at intellij.haskell.external.component.DefinitionLocationComponent$.findDefinitionLocation(DefinitionLocationComponent.scala:55)
	at intellij.haskell.external.component.HaskellComponentsManager$.findDefinitionLocation(HaskellComponentsManager.scala:61)
	at intellij.haskell.navigation.HaskellReference.resolveReferenceByDefinitionLocation(HaskellReference.scala:170)
	at intellij.haskell.navigation.HaskellReference.resolveReference(HaskellReference.scala:162)
	at intellij.haskell.navigation.HaskellReference.$anonfun$multiResolve$1(HaskellReference.scala:129)
	at scala.Option.orElse(Option.scala:306)
	at intellij.haskell.navigation.HaskellReference.multiResolve(HaskellReference.scala:107)
	at com.intellij.psi.PsiPolyVariantReferenceBase.resolve(PsiPolyVariantReferenceBase.java:47)
	at com.intellij.codeInsight.intention.AddAnnotationPsiFix.getContainer(AddAnnotationPsiFix.java:73)
	at com.intellij.codeInspection.dataFlow.EditContractIntention.getTargetMethod(EditContractIntention.java:46)
	at com.intellij.codeInspection.dataFlow.EditContractIntention.isAvailable(EditContractIntention.java:56)
	at com.intellij.codeInsight.intention.impl.ShowIntentionActionsHandler.availableFor(ShowIntentionActionsHandler.java:127)
	at com.intellij.codeInsight.daemon.impl.ShowIntentionsPass.lambda$getActionsToShow$1(ShowIntentionsPass.java:284)
	at com.intellij.codeInsight.intention.impl.ShowIntentionActionsHandler.chooseBetweenHostAndInjected(ShowIntentionActionsHandler.java:152)
	at com.intellij.codeInsight.daemon.impl.ShowIntentionsPass.getActionsToShow(ShowIntentionsPass.java:282)
	at com.intellij.codeInsight.daemon.impl.ShowIntentionsPass.getActionsToShow(ShowIntentionsPass.java:254)
	at com.intellij.codeInsight.daemon.impl.ShowIntentionsPass.doCollectInformation(ShowIntentionsPass.java:220)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:69)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$null$1(PassExecutorService.java:430)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1166)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:423)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:586)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:532)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:86)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:422)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:398)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:164)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:218)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:396)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:174)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

**Comment by rikvdkleij** [comment]
Error message is clear. Check file system permissions.

Can you check if the directory/directories are really not created?

**Comment by rikvdkleij** [comment]
@breandan Is this still an issue?

**Comment by asimaranov** [comment]
I have stumbled upon the same issue. Looks like the plugin is trying to create the cache directory even though it already exists 
```
java.lang.RuntimeException: Could not create directory `C:\Users\andrey\AppData\Local\rikvdkleij\intellij-haskell\cache`
	at intellij.haskell.util.HaskellFileUtil$.createDirectoryIfNotExists(HaskellFileUtil.scala:265)
	at intellij.haskell.GlobalInfo$.getIntelliJHaskellDirectory(GlobalInfo.scala:24)
	at intellij.haskell.GlobalInfo$.getLibrarySourcesPath(GlobalInfo.scala:30)
	at intellij.haskell.util.HaskellProjectUtil$.getProjectLibrarySourcesDirectory(HaskellProjectUtil.scala:77)
	at intellij.haskell.util.HaskellProjectUtil$.isLibraryFile(HaskellProjectUtil.scala:72)
	at intellij.haskell.external.component.DefinitionLocationComponent$.findDefinitionLocationResult(DefinitionLocationComponent.scala:124)
	at intellij.haskell.external.component.DefinitionLocationComponent$.findDefinitionLocation(DefinitionLocationComponent.scala:55)
	at intellij.haskell.external.component.HaskellComponentsManager$.findDefinitionLocation(HaskellComponentsManager.scala:61)
	at intellij.haskell.navigation.HaskellReference.resolveReferenceByDefinitionLocation(HaskellReference.scala:170)
	at intellij.haskell.navigation.HaskellReference.resolveReference(HaskellReference.scala:162)
	at intellij.haskell.navigation.HaskellReference.$anonfun$multiResolve$1(HaskellReference.scala:108)
	at scala.Option.orElse(Option.scala:306)
	at intellij.haskell.navigation.HaskellReference.multiResolve(HaskellReference.scala:107)
	at com.intellij.psi.PsiPolyVariantReferenceBase.resolve(PsiPolyVariantReferenceBase.java:47)
	at com.intellij.codeInsight.intention.AddAnnotationPsiFix.getContainer(AddAnnotationPsiFix.java:73)
	at com.intellij.codeInspection.dataFlow.EditContractIntention.getTargetMethod(EditContractIntention.java:46)
	at com.intellij.codeInspection.dataFlow.EditContractIntention.isAvailable(EditContractIntention.java:56)
	at com.intellij.codeInsight.intention.impl.ShowIntentionActionsHandler.availableFor(ShowIntentionActionsHandler.java:127)
	at com.intellij.codeInsight.daemon.impl.ShowIntentionsPass.lambda$getActionsToShow$1(ShowIntentionsPass.java:284)
	at com.intellij.codeInsight.intention.impl.ShowIntentionActionsHandler.chooseBetweenHostAndInjected(ShowIntentionActionsHandler.java:152)
	at com.intellij.codeInsight.daemon.impl.ShowIntentionsPass.getActionsToShow(ShowIntentionsPass.java:282)
	at com.intellij.codeInsight.daemon.impl.ShowIntentionsPass.getActionsToShow(ShowIntentionsPass.java:254)
	at com.intellij.codeInsight.daemon.impl.ShowIntentionsPass.doCollectInformation(ShowIntentionsPass.java:220)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:69)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$null$1(PassExecutorService.java:430)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1166)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:423)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:586)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:532)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:86)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:422)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:398)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:164)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:218)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:396)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:174)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

**Comment by asimaranov** [comment]
The problem was in the readonly cache directory
![image](https://user-images.githubusercontent.com/25568730/61394335-897cdd80-a8cb-11e9-8255-51395e678ba3.png)

**Comment by rikvdkleij** [comment]
@asimaranov Thanks for the info! Looks like a concurrency issue.

**Comment by rikvdkleij** [comment]
Should be solved in beta52.

**Comment by rikvdkleij** [comment]
Please reopen if still an issue.
