### ISSUE TITLE
Fatal IDE Error on (re)starting the REPL in 2019.+

### ISSUE THREAD

**Issue by enolive** [rikvdkleij/intellij-haskell#456]
it seems there is another IDE error. Unlike the last one (see #419) it is not related to the haskell problems tool window. This time it occurs when the REPL is starting. It seems to have no negative side effect (besides the fatal error tool window hiding all other possible problems).

How to reproduce it (I tested it in both 2019.1.3 and 2019.2):

- create a new haskell project (eg. `stack new my-coolest-project-evar new-template`)
- open it in IntelliJ
- wait for the error tool window to pop up
- you might restart the REPL to make the error  reappear

here is the complete strack trace from the error dialog

```
Details: Current thread: Thread[ApplicationImpl pooled thread 10,4,Idea Thread Group] 208172582
; dispatch thread: false; isDispatchThread(): false
SystemEventQueueThread: Thread[AWT-EventQueue-0 2019.2#IU-192.5728.98 IDEA, eap:false, os:Linux 4.15.0-50-generic, java-version:JetBrains s.r.o 11.0.3+12-b304.10,6,Idea Thread Group] 1433313791

java.lang.Throwable: Read access is allowed from event dispatch thread or inside read-action only (see com.intellij.openapi.application.Application.runReadAction())
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:162)
	at com.intellij.openapi.application.impl.ApplicationImpl.assertReadAccessAllowed(ApplicationImpl.java:1027)
	at com.intellij.psi.impl.source.tree.TreeElement.assertReadAccessAllowed(TreeElement.java:427)
	at com.intellij.psi.impl.source.tree.SharedImplUtil.getParent(SharedImplUtil.java:45)
	at com.intellij.extapi.psi.ASTWrapperPsiElement.getParent(ASTWrapperPsiElement.java:36)
	at com.intellij.psi.PsiWalkingState$PsiTreeGuide.getParent(PsiWalkingState.java:54)
	at com.intellij.psi.PsiWalkingState$PsiTreeGuide.getParent(PsiWalkingState.java:31)
	at com.intellij.util.WalkingState.walkChildren(WalkingState.java:63)
	at com.intellij.util.WalkingState.elementStarted(WalkingState.java:52)
	at com.intellij.psi.PsiWalkingState.elementStarted(PsiWalkingState.java:79)
	at com.intellij.psi.PsiRecursiveElementWalkingVisitor.visitElement(PsiRecursiveElementWalkingVisitor.java:48)
	at com.intellij.psi.util.PsiTreeUtil$4.visitElement(PsiTreeUtil.java:887)
	at com.intellij.psi.PsiElementVisitor.visitFile(PsiElementVisitor.java:34)
	at com.intellij.psi.PsiRecursiveElementWalkingVisitor.visitFile(PsiRecursiveElementWalkingVisitor.java:70)
	at com.intellij.extapi.psi.PsiFileBase.accept(PsiFileBase.java:70)
	at com.intellij.psi.util.PsiTreeUtil.processElements(PsiTreeUtil.java:882)
	at com.intellij.psi.util.PsiTreeUtil.findChildrenOfAnyType(PsiTreeUtil.java:333)
	at com.intellij.psi.util.PsiTreeUtil.collectElementsOfType(PsiTreeUtil.java:866)
	at intellij.haskell.psi.HaskellPsiUtil$.streamChildren(HaskellPsiUtil.scala:222)
	at intellij.haskell.cabal.CabalInfo.executables$lzycompute(CabalInfo.scala:73)
	at intellij.haskell.cabal.CabalInfo.executables(CabalInfo.scala:72)
	at intellij.haskell.cabal.CabalInfo.sourceRoots$lzycompute(CabalInfo.scala:94)
	at intellij.haskell.cabal.CabalInfo.sourceRoots(CabalInfo.scala:94)
	at intellij.haskell.module.HaskellModuleBuilder$.addSourceFolders(HaskellModuleBuilder.scala:164)
	at intellij.haskell.external.component.StackProjectManager$$anon$2.$anonfun$run$19(StackProjectManager.scala:212)
	at intellij.haskell.external.component.StackProjectManager$$anon$2.$anonfun$run$19$adapted(StackProjectManager.scala:210)
	at scala.Option.foreach(Option.scala:274)
	at intellij.haskell.external.component.StackProjectManager$$anon$2.$anonfun$run$18(StackProjectManager.scala:210)
	at com.intellij.openapi.roots.ModuleRootModificationUtil.updateModel(ModuleRootModificationUtil.java:143)
	at intellij.haskell.external.component.StackProjectManager$$anon$2.$anonfun$run$17(StackProjectManager.scala:209)
	at intellij.haskell.external.component.StackProjectManager$$anon$2.$anonfun$run$17$adapted(StackProjectManager.scala:208)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
	at intellij.haskell.external.component.StackProjectManager$$anon$2.$anonfun$run$16(StackProjectManager.scala:208)
	at intellij.haskell.external.component.StackProjectManager$$anon$2.$anonfun$run$16$adapted(StackProjectManager.scala:207)
	at scala.Option.foreach(Option.scala:274)
	at intellij.haskell.external.component.StackProjectManager$$anon$2.run(StackProjectManager.scala:207)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:894)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:169)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:591)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:537)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:156)
	at com.intellij.openapi.progress.impl.CoreProgressManager$4.run(CoreProgressManager.java:408)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:294)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by rikvdkleij** [comment]
Thanks for reporting!
Problem is clear, will fix it.

Weird that you can easily reproduce it. I didn’t see it before.

**Comment by enolive** [comment]
I don't think this error occurs any more with beta52.

However, there seems to be another (maybe unrelated) fatal error with IntelliJ logging on starting a project.

```
java.lang.Throwable: Synchronous execution on EDT: /home/eno-live/.local/bin/stack --numeric-version
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:145)
	at com.intellij.execution.process.OSProcessHandler.checkEdtAndReadAction(OSProcessHandler.java:117)
	at com.intellij.execution.process.OSProcessHandler.waitFor(OSProcessHandler.java:62)
	at com.intellij.execution.process.CapturingProcessRunner.runProcess(CapturingProcessRunner.java:53)
	at com.intellij.execution.process.CapturingProcessHandler.runProcess(CapturingProcessHandler.java:69)
	at intellij.haskell.external.execution.CommandLine$.run3(CommandLine.scala:69)
	at intellij.haskell.external.execution.CommandLine$.run2(CommandLine.scala:55)
	at intellij.haskell.sdk.HaskellSdkType.intellij$haskell$sdk$HaskellSdkType$$getNumericVersion(HaskellSdkType.scala:104)
	at intellij.haskell.sdk.HaskellSdkType.isValidSdkHome(HaskellSdkType.scala:57)
	at intellij.haskell.sdk.HaskellSdkType.getVersionString(HaskellSdkType.scala:74)
	at com.intellij.openapi.projectRoots.SdkType.getVersionString(SdkType.java:79)
	at intellij.haskell.external.component.StackProjectManager.$anonfun$fixSdkStackVersion$1(StackProjectManager.scala:428)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at intellij.haskell.external.component.StackProjectManager.fixSdkStackVersion(StackProjectManager.scala:426)
	at intellij.haskell.external.component.StackProjectManager.projectOpened(StackProjectManager.scala:403)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.lambda$fireProjectOpened$18(ProjectManagerImpl.java:822)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runActivity(StartupManagerImpl.java:467)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.fireProjectOpened(ProjectManagerImpl.java:817)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.lambda$null$5(ProjectManagerImpl.java:397)
	at com.intellij.openapi.application.TransactionGuardImpl.lambda$submitTransactionAndWait$2(TransactionGuardImpl.java:161)
	at com.intellij.openapi.application.TransactionGuardImpl.runSyncTransaction(TransactionGuardImpl.java:82)
	at com.intellij.openapi.application.TransactionGuardImpl.lambda$submitTransaction$1(TransactionGuardImpl.java:106)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:433)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:416)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:399)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:873)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:822)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:461)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:704)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:460)
	at com.intellij.ide.IdeEventQueue.pumpEventsForHierarchy(IdeEventQueue.java:930)
	at com.intellij.openapi.progress.util.ProgressWindow.startBlocking(ProgressWindow.java:205)
	at com.intellij.openapi.progress.util.ProgressWindow.startBlocking(ProgressWindow.java:191)
	at com.intellij.openapi.application.impl.ApplicationImpl.runProcessWithProgressSynchronously(ApplicationImpl.java:566)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcessWithProgressSynchronously(CoreProgressManager.java:459)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.runProcessWithProgressSynchronously(ProgressManagerImpl.java:82)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcessWithProgressSynchronously(CoreProgressManager.java:256)
	at com.intellij.platform.PlatformProjectOpenProcessor.doOpenProject(PlatformProjectOpenProcessor.java:199)
	at com.intellij.ide.RecentProjectsManagerBase.doOpenProject(RecentProjectsManagerBase.java:508)
	at com.intellij.ide.RecentProjectsManagerBase.doReopenLastProject(RecentProjectsManagerBase.java:636)
	at com.intellij.ide.RecentProjectsManagerBase.reopenLastProjectOnStart(RecentProjectsManagerBase.java:614)
	at com.intellij.idea.IdeaApplication$IdeStarter.lambda$main$1(IdeaApplication.java:404)
	at com.intellij.openapi.application.TransactionGuardImpl.runSyncTransaction(TransactionGuardImpl.java:82)
	at com.intellij.openapi.application.TransactionGuardImpl.lambda$submitTransaction$1(TransactionGuardImpl.java:106)
	at com.intellij.openapi.application.TransactionGuardImpl.submitTransaction(TransactionGuardImpl.java:115)
	at com.intellij.openapi.application.TransactionGuard.submitTransaction(TransactionGuard.java:121)
	at com.intellij.idea.IdeaApplication$IdeStarter.main(IdeaApplication.java:400)
	at com.intellij.idea.IdeaApplication.lambda$null$3(IdeaApplication.java:154)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:192)
	at com.intellij.idea.IdeaApplication.lambda$executeInitAppInEdt$5(IdeaApplication.java:154)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:433)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

should I open a new issue?

**Comment by rikvdkleij** [comment]
Is it reproducible? If so, yes please open new issue.

**Comment by rikvdkleij** [comment]
Btw, is it a blocking issue?

**Comment by enolive** [comment]
will do it, thanks! 
It's not a blocking request, just a minor inconvenience.
/close
