### ISSUE TITLE
ProcessNotCreatedException: Cannot run program "/Applications/IntelliJ IDEA.app/Contents/bin"

### ISSUE THREAD

**Issue by runeksvendsen** [rikvdkleij/intellij-haskell#458]
I'm seeing the following error on startup:

<img width="921" alt="Screenshot 2019-08-01 at 10 21 52" src="https://user-images.githubusercontent.com/1069247/62277331-3d42a900-b446-11e9-81f5-36559e4484b9.png">

Full backtrace:

```
com.intellij.execution.process.ProcessNotCreatedException: Cannot run program "/Applications/IntelliJ IDEA.app/Contents/bin" (in directory "/Users/runesvendsen/code/crypto-depth-db"): error=13, Permission denied
java.util.concurrent.CompletionException: com.intellij.execution.process.ProcessNotCreatedException: Cannot run program "/Applications/IntelliJ IDEA.app/Contents/bin" (in directory "/Users/runesvendsen/code/crypto-depth-db"): error=13, Permission denied
	at com.github.benmanes.caffeine.cache.UnboundedLocalCache$UnboundedLocalLoadingCache.lambda$new$0(UnboundedLocalCache.java:935)
	at com.github.benmanes.caffeine.cache.UnboundedLocalCache.lambda$computeIfAbsent$2(UnboundedLocalCache.java:237)
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660)
	at com.github.benmanes.caffeine.cache.UnboundedLocalCache.computeIfAbsent(UnboundedLocalCache.java:233)
	at com.github.benmanes.caffeine.cache.LocalCache.computeIfAbsent(LocalCache.java:111)
	at com.github.benmanes.caffeine.cache.LocalLoadingCache.get(LocalLoadingCache.java:66)
	at com.github.blemale.scaffeine.LoadingCache.get(LoadingCache.scala:30)
	at intellij.haskell.external.component.GlobalProjectInfoComponent$.findGlobalProjectInfo(GlobalProjectInfoComponent.scala:36)
	at intellij.haskell.external.component.HaskellComponentsManager$.getGhcVersion(HaskellComponentsManager.scala:101)
	at intellij.haskell.util.HaskellProjectUtil$.setNoDiagnosticsShowCaretFlag(HaskellProjectUtil.scala:41)
	at intellij.haskell.external.execution.StackCommandLine$.ghcOptions(StackCommandLine.scala:95)
	at intellij.haskell.external.execution.StackCommandLine$.buildInMessageView(StackCommandLine.scala:107)
	at intellij.haskell.external.execution.StackCommandLine$.buildProjectDependenciesInMessageView(StackCommandLine.scala:91)
	at intellij.haskell.external.component.StackProjectManager$$anon$2.run(StackProjectManager.scala:166)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:750)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:580)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:525)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:85)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:144)
	at com.intellij.openapi.progress.impl.CoreProgressManager$4.run(CoreProgressManager.java:395)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:305)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.intellij.execution.process.ProcessNotCreatedException: Cannot run program "/Applications/IntelliJ IDEA.app/Contents/bin" (in directory "/Users/runesvendsen/code/crypto-depth-db"): error=13, Permission denied
	at com.intellij.execution.configurations.GeneralCommandLine.createProcess(GeneralCommandLine.java:395)
	at com.intellij.execution.process.OSProcessHandler.startProcess(OSProcessHandler.java:51)
	at com.intellij.execution.process.OSProcessHandler.<init>(OSProcessHandler.java:44)
	at com.intellij.execution.process.CapturingProcessHandler.<init>(CapturingProcessHandler.java:35)
	at intellij.haskell.external.execution.CommandLine$.createProcessHandler(CommandLine.scala:97)
	at intellij.haskell.external.execution.CommandLine$.run2(CommandLine.scala:61)
	at intellij.haskell.external.execution.CommandLine$.run1(CommandLine.scala:49)
	at intellij.haskell.external.execution.StackCommandLine$.$anonfun$run$1(StackCommandLine.scala:66)
	at scala.Option.map(Option.scala:163)
	at intellij.haskell.external.execution.StackCommandLine$.run(StackCommandLine.scala:58)
	at intellij.haskell.external.component.GlobalProjectInfoComponent$.findPathLines(GlobalProjectInfoComponent.scala:79)
	at intellij.haskell.external.component.GlobalProjectInfoComponent$.createGlobalProjectInfo(GlobalProjectInfoComponent.scala:65)
	at intellij.haskell.external.component.GlobalProjectInfoComponent$.$anonfun$Cache$1(GlobalProjectInfoComponent.scala:32)
	at com.github.blemale.scaffeine.CacheLoaderAdapter.load(CacheLoaderAdapter.java:22)
	at com.github.benmanes.caffeine.cache.UnboundedLocalCache$UnboundedLocalLoadingCache.lambda$new$0(UnboundedLocalCache.java:928)
	... 26 more
Caused by: java.io.IOException: Cannot run program "/Applications/IntelliJ IDEA.app/Contents/bin" (in directory "/Users/runesvendsen/code/crypto-depth-db"): error=13, Permission denied
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at com.intellij.execution.configurations.GeneralCommandLine.startProcess(GeneralCommandLine.java:423)
	at com.intellij.execution.configurations.GeneralCommandLine.createProcess(GeneralCommandLine.java:391)
	... 40 more
Caused by: java.io.IOException: error=13, Permission denied
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 42 more
```

**Comment by rikvdkleij** [comment]
Thanks for reporting!

For some reason you could bypass the mandatory action to set the Haskell SDK. Normally you have to create (by setting the path to the `stack` binary) or choose the Haskell SDK before opening a project.

Can you describe what you actions where before getting this exception?

**Comment by runeksvendsen** [comment]
In the "Welcome to IntelliJ IDEA"-window I clicked "Create New Project", and then I just followed the wizard. I don't recall if the "Choose SDK"-step appeared and I was allowed to click "Next" without choosing an SDK, or if this step simply was never presented to me.

**Comment by rikvdkleij** [comment]
When I follow your steps, I have to choose `Haskell module` in `New project` dialog window. There it's impossible to continue without creating or selecting SDK. 
So I can not reproduce your issue.

**Comment by runeksvendsen** [comment]
I can't reproduce it either.

**Comment by rikvdkleij** [comment]
Shall we close this issue?

**Comment by runeksvendsen** [comment]
Yes 👍
