### ISSUE TITLE
java.lang.Throwable: Assertion failed: Notification should have title and/or content; groupId: Haskell Balloon

### ISSUE THREAD

**Issue by Sir4ur0n** [rikvdkleij/intellij-haskell#502]
Ever since I upgraded to 57 (from 52) I get this exception:
```
java.lang.Throwable: Assertion failed: Notification should have title and/or content; groupId: Haskell Balloon
	at com.intellij.openapi.diagnostic.Logger.assertTrue(Logger.java:180)
	at com.intellij.notification.Notification.assertHasTitleOrContent(Notification.java:362)
	at com.intellij.notification.Notifications$Bus.notify(Notifications.java:65)
	at com.intellij.notification.Notification.notify(Notification.java:340)
	at intellij.haskell.HaskellNotificationGroup$.log(HaskellNotificationGroup.scala:130)
	at intellij.haskell.HaskellNotificationGroup$.balloonEvent(HaskellNotificationGroup.scala:125)
	at intellij.haskell.HaskellNotificationGroup$.logErrorBalloonEvent(HaskellNotificationGroup.scala:74)
	at intellij.haskell.external.execution.StackCommandLine$.$anonfun$installTool$1(StackCommandLine.scala:91)
	at intellij.haskell.external.execution.StackCommandLine$.$anonfun$installTool$1$adapted(StackCommandLine.scala:83)
	at scala.Option.exists(Option.scala:406)
	at intellij.haskell.external.execution.StackCommandLine$.installTool(StackCommandLine.scala:83)
	at intellij.haskell.external.component.StackProjectManager$$anon$1.isToolAvailable(StackProjectManager.scala:116)
	at intellij.haskell.external.component.StackProjectManager$$anon$1.$anonfun$run$2(StackProjectManager.scala:132)
	at intellij.haskell.external.component.StackProjectManager$$anon$1.$anonfun$run$2$adapted(StackProjectManager.scala:132)
	at scala.Option.foreach(Option.scala:437)
	at intellij.haskell.external.component.StackProjectManager$$anon$1.run(StackProjectManager.scala:132)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:894)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:169)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:591)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:537)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:156)
	at com.intellij.openapi.progress.impl.CoreProgressManager$4.run(CoreProgressManager.java:408)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:294)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:835)
```

And indeed I get an empty notification:
![image](https://user-images.githubusercontent.com/1204125/72713073-a7721600-3b6c-11ea-9f1b-0e0cdfad5a5d.png)
![image](https://user-images.githubusercontent.com/1204125/72713088-accf6080-3b6c-11ea-9b33-0ea75292f414.png)

**Comment by rikvdkleij** [comment]
Thanks for reporting!

I can suppress this exception but I wonder why installing Hoogle returns with exit code not equal to 0. Is there some info in the progress bar?

**Comment by Sir4ur0n** [comment]
What do you mean, the progress bar?

I don't have anything else in the event log though.

Could this be related to me using Nix[OS]? If I remember in https://github.com/rikvdkleij/intellij-haskell/issues/455 I had to manually install stuff for it to work. However back in the days, the failed command was printed in the event log, now there's nothing... I'll give it a try

**Comment by Sir4ur0n** [comment]
Ok it seems to work when I manually did the same install as #455 but with LTS 14, I guess we can close this issue as I see you have submitted a commit to actually put content in the balloon ^^

Cheers and thank you!
