### ISSUE TITLE
NoSuchMethodError NonBlockingReadAction.cancelWith in beta 58

### ISSUE THREAD

**Issue by Sir4ur0n** [rikvdkleij/intellij-haskell#506]
Ever since upgrading to beta 58 I get this exception as soon as Intellij starts my project:
```java
java.lang.NoSuchMethodError: com.intellij.openapi.application.NonBlockingReadAction.cancelWith(Lcom/intellij/openapi/progress/ProgressIndicator;)Lcom/intellij/openapi/application/NonBlockingReadAction;
	at intellij.haskell.util.ApplicationUtil$.$anonfun$runReadAction$1(ApplicationUtil.scala:45)
	at scala.Option.foreach(Option.scala:437)
	at intellij.haskell.util.ApplicationUtil$.runReadAction(ApplicationUtil.scala:45)
	at intellij.haskell.cabal.CabalInfo.executables$lzycompute(CabalInfo.scala:78)
	at intellij.haskell.cabal.CabalInfo.executables(CabalInfo.scala:76)
	at intellij.haskell.cabal.CabalInfo.sourceRoots$lzycompute(CabalInfo.scala:106)
	at intellij.haskell.cabal.CabalInfo.sourceRoots(CabalInfo.scala:106)
	at intellij.haskell.external.component.StackProjectManager$$anon$2.$anonfun$run$46(StackProjectManager.scala:353)
	at intellij.haskell.external.component.StackProjectManager$$anon$2.$anonfun$run$46$adapted(StackProjectManager.scala:352)
	at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:553)
	at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:551)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:921)
	at intellij.haskell.external.component.StackProjectManager$$anon$2.$anonfun$run$45(StackProjectManager.scala:352)
	at intellij.haskell.external.component.StackProjectManager$$anon$2.$anonfun$run$45$adapted(StackProjectManager.scala:352)
	at scala.Option.foreach(Option.scala:437)
	at intellij.haskell.external.component.StackProjectManager$$anon$2.run(StackProjectManager.scala:352)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:894)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:169)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:591)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:537)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:156)
	at com.intellij.openapi.progress.impl.CoreProgressManager$4.run(CoreProgressManager.java:408)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:294)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:835)
```

**Comment by rikvdkleij** [comment]
You need to upgrade IntelliJ. Will fix that in next version by setting minimum version.

**Comment by Sir4ur0n** [comment]
Indeed, as I am on NixOS 19.09 I didn't have Intellij 2019.3 yet. My bad, we can close :smile:
