### ISSUE TITLE
Unhandled exception in beta63

### ISSUE THREAD

**Issue by develop7** [rikvdkleij/intellij-haskell#518]
Not sure of the reproduction steps

<details>
<summary>Stack trace</summary>

```
java.lang.NullPointerException
	at intellij.haskell.external.component.StackProjectManager$$anon$2$$anon$3.$anonfun$invalidateTypeInfo$4(StackProjectManager.scala:319)
	at intellij.haskell.external.component.StackProjectManager$$anon$2$$anon$3.$anonfun$invalidateTypeInfo$4$adapted(StackProjectManager.scala:319)
	at scala.Option.filter(Option.scala:319)
	at intellij.haskell.external.component.StackProjectManager$$anon$2$$anon$3.$anonfun$invalidateTypeInfo$3(StackProjectManager.scala:319)
	at scala.Option.orElse(Option.scala:477)
	at intellij.haskell.external.component.StackProjectManager$$anon$2$$anon$3.invalidateTypeInfo(StackProjectManager.scala:319)
	at intellij.haskell.external.component.StackProjectManager$$anon$2$$anon$3.childrenChanged(StackProjectManager.scala:329)
	at com.intellij.psi.impl.PsiManagerImpl.fireEvent(PsiManagerImpl.java:391)
	at com.intellij.psi.impl.PsiManagerImpl.childrenChanged(PsiManagerImpl.java:297)
	at com.intellij.psi.impl.file.impl.FileManagerImpl.forceReload(FileManagerImpl.java:133)
	at com.intellij.psi.impl.file.impl.PsiVFSListener.propertyChanged(PsiVFSListener.java:316)
	at com.intellij.psi.impl.file.impl.PsiVFSListener.fireForGrouped(PsiVFSListener.java:701)
	at one.util.streamex.CollapseSpliterator.lambda$forEachRemaining$0(CollapseSpliterator.java:131)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1654)
	at one.util.streamex.CollapseSpliterator.forEachRemaining(CollapseSpliterator.java:127)
	at one.util.streamex.AbstractStreamEx.forEach(AbstractStreamEx.java:306)
	at com.intellij.psi.impl.file.impl.PsiVFSListener.groupAndFire(PsiVFSListener.java:674)
	at com.intellij.psi.impl.file.impl.PsiVFSListener.after(PsiVFSListener.java:663)
	at com.intellij.psi.impl.file.impl.PsiVFSListener$2.after(PsiVFSListener.java:108)
	at jdk.internal.reflect.GeneratedMethodAccessor121.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.intellij.util.messages.impl.MessageBusImpl.invokeListener(MessageBusImpl.java:513)
	at com.intellij.util.messages.impl.MessageBusConnectionImpl.deliverMessage(MessageBusConnectionImpl.java:142)
	at com.intellij.util.messages.impl.MessageBusImpl.doPumpMessages(MessageBusImpl.java:438)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpWaitingBuses(MessageBusImpl.java:398)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:388)
	at com.intellij.util.messages.impl.MessageBusImpl.sendMessage(MessageBusImpl.java:372)
	at com.intellij.util.messages.impl.MessageBusImpl.lambda$createTopicHandler$1(MessageBusImpl.java:241)
	at com.sun.proxy.$Proxy117.after(Unknown Source)
	at com.intellij.util.FileContentUtilCore.lambda$reparseFiles$0(FileContentUtilCore.java:50)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:885)
	at com.intellij.util.FileContentUtilCore.reparseFiles(FileContentUtilCore.java:38)
	at com.intellij.util.FileContentUtil.reparseFiles(FileContentUtil.java:72)
	at org.intellij.plugins.intelliLang.inject.InjectLanguageAction.invokeImpl(InjectLanguageAction.java:214)
	at org.intellij.plugins.intelliLang.inject.InjectLanguageAction.invokeImpl(InjectLanguageAction.java:150)
	at org.intellij.plugins.intelliLang.inject.InjectLanguageAction.lambda$null$1(InjectLanguageAction.java:140)
	at com.intellij.openapi.application.ReadAction.lambda$run$1(ReadAction.java:64)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:821)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:71)
	at com.intellij.openapi.application.ReadAction.run(ReadAction.java:64)
	at org.intellij.plugins.intelliLang.inject.InjectLanguageAction.lambda$invoke$2(InjectLanguageAction.java:136)
	at org.intellij.plugins.intelliLang.inject.InjectLanguageAction.lambda$doChooseLanguageToInject$5(InjectLanguageAction.java:255)
	at com.intellij.ui.popup.PopupListAdapter.lambda$setItemChosenCallback$0(PopupListAdapter.java:59)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:193)
	at com.intellij.ui.popup.AbstractPopup.lambda$dispose$13(AbstractPopup.java:1434)
	at com.intellij.util.ui.UIUtil.invokeLaterIfNeeded(UIUtil.java:2418)
	at com.intellij.ide.IdeEventQueue.ifFocusEventsInTheQueue(IdeEventQueue.java:177)
	at com.intellij.ide.IdeEventQueue.executeWhenAllFocusEventsLeftTheQueue(IdeEventQueue.java:129)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.doWhenFocusSettlesDown(FocusManagerImpl.java:159)
	at com.intellij.openapi.wm.impl.IdeFocusManagerImpl.doWhenFocusSettlesDown(IdeFocusManagerImpl.java:36)
	at com.intellij.ui.popup.AbstractPopup.dispose(AbstractPopup.java:1430)
	at com.intellij.openapi.util.ObjectNode.lambda$execute$0(ObjectNode.java:104)
	at com.intellij.openapi.util.ObjectTree.executeActionWithRecursiveGuard(ObjectTree.java:183)
	at com.intellij.openapi.util.ObjectNode.execute(ObjectNode.java:71)
	at com.intellij.openapi.util.ObjectTree.executeAll(ObjectTree.java:133)
	at com.intellij.openapi.util.Disposer.dispose(Disposer.java:123)
	at com.intellij.ui.popup.AbstractPopup.cancel(AbstractPopup.java:735)
	at com.intellij.ui.popup.AbstractPopup.closeOk(AbstractPopup.java:667)
	at com.intellij.openapi.ui.popup.PopupChooserBuilder.closePopup(PopupChooserBuilder.java:454)
	at com.intellij.openapi.ui.popup.PopupChooserBuilder.access$100(PopupChooserBuilder.java:32)
	at com.intellij.openapi.ui.popup.PopupChooserBuilder$2.actionPerformed(PopupChooserBuilder.java:443)
	at java.desktop/javax.swing.JComponent$ActionStandin.actionPerformed(JComponent.java:3443)
	at java.desktop/javax.swing.SwingUtilities.notifyAction(SwingUtilities.java:1810)
	at java.desktop/javax.swing.JComponent.processKeyBinding(JComponent.java:2900)
	at java.desktop/javax.swing.JComponent.processKeyBindings(JComponent.java:2962)
	at java.desktop/javax.swing.JComponent.processKeyEvent(JComponent.java:2862)
	at java.desktop/java.awt.Component.processEvent(Component.java:6428)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5026)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4858)
	at java.desktop/java.awt.KeyboardFocusManager.redispatchEvent(KeyboardFocusManager.java:1950)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.dispatchKeyEvent(DefaultKeyboardFocusManager.java:878)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.preDispatchKeyEvent(DefaultKeyboardFocusManager.java:1148)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(DefaultKeyboardFocusManager.java:1017)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:843)
	at com.intellij.ide.IdeKeyboardFocusManager.dispatchEvent(IdeKeyboardFocusManager.java:40)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4907)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2773)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4858)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:778)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:751)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:749)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:748)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:908)
	at com.intellij.ide.IdeEventQueue.dispatchKeyEvent(IdeEventQueue.java:834)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:775)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:424)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:698)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:423)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

</details>

**Comment by rikvdkleij** [comment]
Thanks for reporting!

**Comment by rikvdkleij** [comment]
Should be fixed in beta64

**Comment by rikvdkleij** [comment]
Please reopen if still an issue.
