### ISSUE TITLE
AssertionError: Already disposed: Project

### ISSUE THREAD

**Issue by dima74** [rikvdkleij/intellij-haskell#520]
Exception:

```
java.lang.AssertionError: Already disposed: Project (name=formal-languages, containerState=DISPOSE_COMPLETED, componentStore=/home/dima/2m/formal/github) 
	at com.intellij.openapi.components.impl.ComponentManagerImpl.lambda$throwAlreadyDisposed$0(ComponentManagerImpl.java:153)
	at com.intellij.openapi.application.ReadAction.lambda$run$1(ReadAction.java:64)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:825)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:71)
	at com.intellij.openapi.application.ReadAction.run(ReadAction.java:64)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.throwAlreadyDisposed(ComponentManagerImpl.java:151)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.getPicoContainer(ComponentManagerImpl.java:144)
	at com.intellij.serviceContainer.PlatformComponentManagerImpl.getService(PlatformComponentManagerImpl.kt:286)
	at com.intellij.openapi.components.ComponentManager.getService(ComponentManager.java:114)
	at com.intellij.codeInsight.documentation.DocumentationManager.getInstance(DocumentationManager.java:227)
	at intellij.haskell.external.component.LoadComponent$.$anonfun$load$2(LoadComponent.scala:74)
	at intellij.haskell.util.ScalaUtil$.$anonfun$runnable$1(ScalaUtil.scala:35)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:238)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

Plugin version: 1.0.0-beta63

System info:

```
IntelliJ IDEA 2019.3.3 (Ultimate Edition)
Build #IU-193.6494.35, built on February 11, 2020
Runtime version: 11.0.5+10-b520.38 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 5.5.6-arch1-1
GC: ParNew, ConcurrentMarkSweep
Memory: 8125M
Cores: 8
Registry: ide.balloon.shadow.size=0
Non-Bundled Plugins: BashSupport, com.mnw.tabmover, com.wakatime.intellij.plugin, indent-rainbow.indent-rainbow, intellij.haskell, org.jetbrains.idea.grammar, org.toml.lang, org.rust.lang
```

Thanks for the plugin!

**Comment by rikvdkleij** [comment]
Thanks for reporting!

**Comment by rikvdkleij** [comment]
Should be fixed in beta64

**Comment by Miraclelucy** [comment]
Given the nature of the error, I've managed to find a workaround:

Disabling the proxy configured inside IntelliJ settings.
Sync.
Re-enable the configured proxy.
Sync should still work.

**Comment by rikvdkleij** [comment]
Please reopen if still an issue.
