### ISSUE TITLE
Type prompt dialog won't appear when the mouse on type string.

### ISSUE THREAD

**Issue by CanftIn** [rikvdkleij/intellij-haskell#529]
![image](https://user-images.githubusercontent.com/26135447/77530083-befeaf80-6ecb-11ea-93a7-6340338110aa.png)

The type dialog like the image above`System.IO.putStrLn :: String -> IO ()` won't appear in intellij idea.
**Platform:** Windows
**version:** 1.0.0-beta52
```
Stack version: 2.1.3

GHC: 8.8.3

HLint: HLint v2.1.11, (C) Neil Mitchell 2006-2018

Hoogle: Hoogle 5.0.17.3, http://hoogle.haskell.org/

Hindent: hindent 5.3.1

Stylish-haskell: stylish-haskell 0.9.2.2
```

**Comment by rikvdkleij** [comment]
Work other plugin features? 

Are there errors in the Haskell Event log. To enable the Event log see https://github.com/rikvdkleij/intellij-haskell#getting-started

Btw, for better support for GHC 8.8.3 you can install the latest beta, beta63. See https://github.com/rikvdkleij/intellij-haskell#installing-latest-beta-of-the-plugin

**Comment by CanftIn** [comment]
The plugin repl and runner work.
I've reinstalled the beta63 plugin.

Important fail message `[global-stack-repl] stdout: -- not currently imported`
log output:
[log.txt](https://github.com/rikvdkleij/intellij-haskell/files/4385136/log.txt)

And there occur a exception in IDE Fatal Errors.
```
java.nio.charset.MalformedInputException: Input length = 1
	at java.base/java.nio.charset.CoderResult.throwException(CoderResult.java:274)
	at java.base/sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:339)
	at java.base/sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
	at java.base/java.io.InputStreamReader.read(InputStreamReader.java:185)
	at java.base/java.io.BufferedReader.fill(BufferedReader.java:161)
	at java.base/java.io.BufferedReader.readLine(BufferedReader.java:326)
	at java.base/java.io.BufferedReader.readLine(BufferedReader.java:392)
	at scala.io.BufferedSource$BufferedLineIterator.hasNext(BufferedSource.scala:73)
	at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:553)
	at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:551)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1274)
	at intellij.haskell.external.repl.StackRepl.$anonfun$start$7(StackRepl.scala:246)
	at intellij.haskell.external.repl.StackRepl.$anonfun$start$7$adapted(StackRepl.scala:246)
	at scala.sys.process.ProcessBuilderImpl$Simple.$anonfun$run$4(ProcessBuilderImpl.scala:91)
	at scala.sys.process.ProcessImpl$Spawn$$anon$1.run(ProcessImpl.scala:25)
```

**Comment by rikvdkleij** [comment]
This issue looks related to your project. Encoding issue? 

Maybe this helps:
https://www.reddit.com/r/haskell/comments/7s4yrv/i_figured_out_how_to_display_chineseunicode_in/

**Comment by rikvdkleij** [comment]
Please reopen if still an issue.
