### ISSUE TITLE
ui unresponsive: AbstractPopup.show

### ISSUE THREAD

**Issue by aryairani** [rikvdkleij/intellij-haskell#560]
[threadDumps-freeze-20200514-145208-IC-201.7223.91-AbstractPopup.show-11sec.zip](https://github.com/rikvdkleij/intellij-haskell/files/4630307/threadDumps-freeze-20200514-145208-IC-201.7223.91-AbstractPopup.show-11sec.zip)

Let me know if there's anything I can do to filter these freeze reports before tossing them over the wall to you!

**Comment by rikvdkleij** [comment]
Thanks!

I see again this 
`"BaseDataReader: error stream of fsnotifier"`

> Let me know if there's anything I can do to filter these freeze reports before tossing them over the wall to you!

You have to search for `haskell` and see something else then REPLs which are running, like for example:
```
"Simple-output-spawn-Thread-10" prio=0 tid=0x0 nid=0x0 runnable
     java.lang.Thread.State: RUNNABLE
 (in native)
	at java.base@11.0.6/java.io.FileInputStream.readBytes(Native Method)
	at java.base@11.0.6/java.io.FileInputStream.read(FileInputStream.java:279)
	at java.base@11.0.6/java.io.BufferedInputStream.read1(BufferedInputStream.java:290)
	at java.base@11.0.6/java.io.BufferedInputStream.read(BufferedInputStream.java:351)
	at java.base@11.0.6/sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284)
	at java.base@11.0.6/sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
	at java.base@11.0.6/sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
	at java.base@11.0.6/java.io.InputStreamReader.read(InputStreamReader.java:185)
	at java.base@11.0.6/java.io.BufferedReader.fill(BufferedReader.java:161)
	at java.base@11.0.6/java.io.BufferedReader.readLine(BufferedReader.java:326)
	at java.base@11.0.6/java.io.BufferedReader.readLine(BufferedReader.java:392)
	at scala.io.BufferedSource$BufferedLineIterator.hasNext(BufferedSource.scala:73)
	at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:553)
	at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:551)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1274)
	at intellij.haskell.external.repl.StackRepl.$anonfun$start$5(StackRepl.scala:245)
	at intellij.haskell.external.repl.StackRepl.$anonfun$start$5$adapted(StackRepl.scala:245)
	at intellij.haskell.external.repl.StackRepl$$Lambda$3651/0x00000008020eb840.apply(Unknown Source)
	at scala.sys.process.ProcessBuilderImpl$Simple.$anonfun$run$3(ProcessBuilderImpl.scala:88)
	at scala.sys.process.ProcessBuilderImpl$Simple$$Lambda$3658/0x00000008020efc40.apply$mcV$sp(Unknown Source)
	at scala.sys.process.ProcessImpl$Spawn$$anon$1.run(ProcessImpl.scala:25)
```

**Comment by aryairani** [comment]
> You have to search for haskell and see something else then REPLs which are running

Ok, will do!
