### ISSUE TITLE
Error on creating Haskell project

### ISSUE THREAD

**Issue by CraftSpider** [rikvdkleij/intellij-haskell#567]
Freshly installed the plugin and stack
Plugin version: 1.0.0-beta73
Stack version: 2.3.1
Error Message: `Error adding module to project: null`

Seems similar to #250

**Comment by rikvdkleij** [comment]
Thanks for reporting!

I can't reproduce your issue. 

Guess that `stack new` couldn't create the files for some reason.

**Comment by CraftSpider** [comment]
Running `stack new [name]` or `stack new [name] --bare` works fine from command line, so I'm not sure why the IDE is failing to create the files. I don't know much about plugin debugging or I'd look for the actual error. It works with importing existing for now, so I'll stick with that.

**Comment by rikvdkleij** [comment]
Which OS? 
In case Windows, issue can be that path contains spaces or is too long. Or a permission issue.

**Comment by CraftSpider** [comment]
The path to the stack executable does have a space in it, that is quite probably the issue. I'll try moving it somewhere without a space

**Comment by maartenh** [comment]
I'm seeing the same error with 1.0.0-beta78 on IDEA version 2020.2 (and also reproduced on 2020.1.2).
This is on Mac OS with a homebrew install of stack (no spaces in the path).

I picked the following bit with a stacktrace out of the idea.log
```
2020-08-01 22:55:18,264 [ 218975]   INFO - BridgeProjectLifecycleListener - Using legacy project model to open project 
2020-08-01 22:55:18,287 [ 218998]   INFO - rojectCodeStyleSettingsManager - Initialized from default code style settings. 
2020-08-01 22:55:18,352 [ 219063]  ERROR - plication.impl.ApplicationImpl - EventQueue.isDispatchThread()=false Toolkit.getEventQueue()=com.intellij.ide.IdeEventQueue@67fbad5b
Current thread: Thread[ApplicationImpl pooled thread 29,4,Idea Thread Group] 135524030
Write thread (volatile): Thread[AWT-EventQueue-0,6,Idea Thread Group] 352582126com.intellij.openapi.diagnostic.Attachment@402bf9ce 
com.intellij.openapi.diagnostic.RuntimeExceptionWithAttachments: EventQueue.isDispatchThread()=false Toolkit.getEventQueue()=com.intellij.ide.IdeEventQueue@67fbad5b
Current thread: Thread[ApplicationImpl pooled thread 29,4,Idea Thread Group] 135524030
Write thread (volatile): Thread[AWT-EventQueue-0,6,Idea Thread Group] 352582126com.intellij.openapi.diagnostic.Attachment@402bf9ce
	at com.intellij.openapi.application.impl.ApplicationImpl.assertIsWriteThread(ApplicationImpl.java:1072)
	at com.intellij.openapi.application.impl.ApplicationImpl.startWrite(ApplicationImpl.java:1157)
	at com.intellij.openapi.application.impl.ApplicationImpl.access$300(ApplicationImpl.java:62)
	at com.intellij.openapi.application.impl.ApplicationImpl$WriteAccessToken.<init>(ApplicationImpl.java:1225)
	at com.intellij.openapi.application.impl.ApplicationImpl.acquireWriteActionLock(ApplicationImpl.java:1217)
	at com.intellij.openapi.application.WriteAction.start(WriteAction.java:92)
	at com.intellij.openapi.application.WriteAction.run(WriteAction.java:100)
	at intellij.haskell.module.HaskellModuleBuilder.$anonfun$createModule$1(HaskellModuleBuilder.scala:123)
	at intellij.haskell.util.ScalaUtil$.$anonfun$runnable$1(ScalaUtil.scala:35)
	at com.intellij.util.RunnableCallable.call(RunnableCallable.java:20)
	at com.intellij.util.RunnableCallable.call(RunnableCallable.java:11)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.call(ApplicationImpl.java:268)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:834)
2020-08-01 22:55:18,352 [ 219063]  ERROR - plication.impl.ApplicationImpl - IntelliJ IDEA 2020.2  Build #IU-202.6397.94 
2020-08-01 22:55:18,352 [ 219063]  ERROR - plication.impl.ApplicationImpl - JDK: 11.0.7; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o. 
2020-08-01 22:55:18,352 [ 219063]  ERROR - plication.impl.ApplicationImpl - OS: Mac OS X 
2020-08-01 22:55:18,352 [ 219063]  ERROR - plication.impl.ApplicationImpl - Plugin to blame: IntelliJ-Haskell version: 1.0.0-beta78 
2020-08-01 22:55:18,352 [ 219063]  ERROR - plication.impl.ApplicationImpl - Last Action: EditorBackSpace 
2020-08-01 22:55:18,353 [ 219064]   WARN - il.projectWizard.ModuleBuilder -  
java.lang.NullPointerException
	at intellij.haskell.module.HaskellModuleBuilder$.addSourceFolders(HaskellModuleBuilder.scala:181)
	at intellij.haskell.module.HaskellModuleBuilder.setupRootModel(HaskellModuleBuilder.scala:87)
	at com.intellij.ide.util.projectWizard.ModuleBuilder.setupModule(ModuleBuilder.java:260)
	at intellij.haskell.module.HaskellModuleBuilder.createModule(HaskellModuleBuilder.scala:135)
	at com.intellij.ide.util.projectWizard.ModuleBuilder.createAndCommitIfNeeded(ModuleBuilder.java:292)
	at com.intellij.ide.util.projectWizard.ModuleBuilder.lambda$commitModule$4(ModuleBuilder.java:338)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteActionWithClass(ApplicationImpl.java:968)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:994)
	at com.intellij.ide.util.projectWizard.ModuleBuilder.commitModule(ModuleBuilder.java:337)
	at com.intellij.platform.templates.TemplateModuleBuilder.commitModule(TemplateModuleBuilder.java:134)
	at com.intellij.ide.util.projectWizard.ModuleBuilder.commit(ModuleBuilder.java:323)
	at com.intellij.ide.impl.NewProjectUtil.doCreate(NewProjectUtil.java:146)
	at com.intellij.ide.impl.NewProjectUtil.createFromWizard(NewProjectUtil.java:74)
	at com.intellij.ide.impl.NewProjectUtil.createFromWizard(NewProjectUtil.java:69)
	at com.intellij.ide.impl.NewProjectUtil.createNewProject(NewProjectUtil.java:64)
	at com.intellij.ide.actions.NewProjectAction.actionPerformed(NewProjectAction.java:24)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:282)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.invokeAction(ActionUtil.java:446)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.invokeAction(ActionUtil.java:431)
	at com.intellij.ui.components.labels.ActionLink$1.linkSelected(ActionLink.java:47)
	at com.intellij.ui.components.labels.LinkLabel.doClick(LinkLabel.java:138)
	at com.intellij.ui.components.labels.ActionLink.doClick(ActionLink.java:56)
	at com.intellij.ui.components.labels.LinkLabel$MyMouseHandler.mouseReleased(LinkLabel.java:322)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6650)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3345)
	at java.desktop/java.awt.Component.processEvent(Component.java:6415)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5025)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4857)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2773)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4857)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:778)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:751)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:749)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:748)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:967)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:904)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:836)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:450)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:744)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:449)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:802)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:503)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by maartenh** [comment]
@rikvdkleij Is the above stacktrace any help in finding the cause of this issue?

**Comment by rikvdkleij** [comment]
@maartenh It looks like this NPE occurs because there is no Cabal file. The plugin uses stack to create a new project from a template using `stack new`. Can you check if this works from the command line?

**Comment by maartenh** [comment]
@rikvdkleij I tested it, and `stack new <packagename>` works on the command line.

However, a bit more experimenting showed what the actual problem is.
I was just getting started with a book on Haskell, and was trying to create a project/package called "Chapter-01". Which `stack new` on the command line explains is an invalid package name, leading to it not creating the project, and the subsequent missing Cabal file.

Perhaps a check on the project/package name would be helpful for people new to Haskell.

**Comment by rikvdkleij** [comment]
@maartenh Great you found the cause!

> Perhaps a check on the project/package name would be helpful for people new to Haskell.

Yes, that's a good idea. Also have to prevent the NPE.

**Comment by chriswakare** [comment]
We get an error if the Project Name has "spaces" or even and underscore "_".
For now the workaround can be 
- Do not use spaces or special characters like "_"

**Comment by perryprog** [comment]
Strangely, I get this same issue when using a hyphen (or any other invalid characters) in the project name. I get the same error dialog at project creation, and am then dumped into the folder which only has an `.idea/` directory. There is also an exception thrown, which is possibly related.

This is on a laptop that has a pretty fresh environment, so this is a fresh install of Intellij IDEA 2020.2.1.
- GHC 8.10.2
- Stack 2.33
- Cabal 3.2.0.0
- Plugin version 1.0.0-beta78

```
Write access is allowed from write thread only

com.intellij.openapi.diagnostic.RuntimeExceptionWithAttachments: EventQueue.isDispatchThread()=false Toolkit.getEventQueue()=com.intellij.ide.IdeEventQueue@8fa40bb
Current thread: Thread[ApplicationImpl pooled thread 34,4,Idea Thread Group] 921257332
Write thread (volatile): Thread[AWT-EventQueue-0,6,Idea Thread Group] 203919821com.intellij.openapi.diagnostic.Attachment@7c3a0684
	at com.intellij.openapi.application.impl.ApplicationImpl.assertIsWriteThread(ApplicationImpl.java:1072)
	at com.intellij.openapi.application.impl.ApplicationImpl.startWrite(ApplicationImpl.java:1157)
	at com.intellij.openapi.application.impl.ApplicationImpl.access$300(ApplicationImpl.java:62)
	at com.intellij.openapi.application.impl.ApplicationImpl$WriteAccessToken.<init>(ApplicationImpl.java:1225)
	at com.intellij.openapi.application.impl.ApplicationImpl.acquireWriteActionLock(ApplicationImpl.java:1217)
	at com.intellij.openapi.application.WriteAction.start(WriteAction.java:92)
	at com.intellij.openapi.application.WriteAction.run(WriteAction.java:100)
	at intellij.haskell.module.HaskellModuleBuilder.$anonfun$createModule$1(HaskellModuleBuilder.scala:123)
	at intellij.haskell.util.ScalaUtil$.$anonfun$runnable$1(ScalaUtil.scala:35)
	at com.intellij.util.RunnableCallable.call(RunnableCallable.java:20)
	at com.intellij.util.RunnableCallable.call(RunnableCallable.java:11)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.call(ApplicationImpl.java:268)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by rikvdkleij** [comment]
Should be solved in latest versions. Please reopen if still an issue.
