### ISSUE TITLE
Internal error: ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by p0lunin** [rikvdkleij/intellij-haskell#586]
**IntelliJ IDEA 2020.1.2** (Community Edition)
**Build** #IC-201.7846.76, built on June 1, 2020
**Runtime version**: 11.0.7+10-b765.53 amd64
**VM**: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
**Version of plugin**: 1.0.0-beta75

I don't know how to repoduce it
Full error:
```
java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
	at intellij.haskell.util.ScalaUtil$.$anonfun$linesToMap$2(ScalaUtil.scala:73)
	at scala.collection.StrictOptimizedIterableOps.map(StrictOptimizedIterableOps.scala:99)
	at scala.collection.StrictOptimizedIterableOps.map$(StrictOptimizedIterableOps.scala:86)
	at scala.collection.mutable.ListBuffer.map(ListBuffer.scala:37)
	at intellij.haskell.util.ScalaUtil$.linesToMap(ScalaUtil.scala:71)
	at intellij.haskell.external.component.LibraryPackageInfoComponent$.findPackageInfo(LibraryPackageInfoComponent.scala:109)
	at intellij.haskell.external.component.LibraryPackageInfoComponent$.$anonfun$preloadLibraryPackageInfos$4(LibraryPackageInfoComponent.scala:61)
	at scala.collection.ArrayOps$.map$extension(ArrayOps.scala:924)
	at intellij.haskell.external.component.LibraryPackageInfoComponent$.$anonfun$preloadLibraryPackageInfos$3(LibraryPackageInfoComponent.scala:59)
	at scala.Option.map(Option.scala:242)
	at intellij.haskell.external.component.LibraryPackageInfoComponent$.preloadLibraryPackageInfos(LibraryPackageInfoComponent.scala:56)
	at intellij.haskell.external.component.StackProjectManager$$anon$2.run(StackProjectManager.scala:298)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:932)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsync$5(CoreProgressManager.java:434)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$null$3(ProgressRunner.java:233)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:166)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:627)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:572)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:61)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:153)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:233)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by rikvdkleij** [comment]
Thanks for reporting!

A line of the output of `ghc-pkg dump` did not contain a `:` to split the line up to a key and a value.
Will fix it by skipping this line.

**Comment by rikvdkleij** [comment]
Should be fixed in beta76

**Comment by rikvdkleij** [comment]
Please reopen if still an issue.
