### ISSUE TITLE
java.lang.UnsupportedOperationException: init of empty array

### ISSUE THREAD

**Issue by harcokuppens** [rikvdkleij/intellij-haskell#598]
on Macos catalina in IDEA CE-2020.1 I get the following error with the plugin version v1.0.0-beta78:   

    java.lang.UnsupportedOperationException: init of empty array
    	at scala.collection.ArrayOps$.init$extension(ArrayOps.scala:340)
    	at intellij.haskell.external.component.BrowseModuleComponent$.$anonfun$createLibraryModuleIdentifier$2(BrowseModuleComponent.scala:163)
    	at scala.Option.map(Option.scala:242)
    	at intellij.haskell.external.component.BrowseModuleComponent$.$anonfun$createLibraryModuleIdentifier$1(BrowseModuleComponent.scala:163)
    	at scala.Option.map(Option.scala:242)
    	at intellij.haskell.external.component.BrowseModuleComponent$.createLibraryModuleIdentifier(BrowseModuleComponent.scala:160)
    	at intellij.haskell.external.component.BrowseModuleComponent$.$anonfun$findLibraryModuleIdentifiers$1(BrowseModuleComponent.scala:145)
    	at scala.collection.immutable.List.flatMap(List.scala:293)
    	at scala.collection.immutable.List.flatMap(List.scala:79)
    	at intellij.haskell.external.component.BrowseModuleComponent$.findLibraryModuleIdentifiers(BrowseModuleComponent.scala:145)
    	at intellij.haskell.external.component.BrowseModuleComponent$.findModuleIdentifiers(BrowseModuleComponent.scala:107)
    	at intellij.haskell.external.component.BrowseModuleComponent$.$anonfun$Cache$1(BrowseModuleComponent.scala:39)
    	at com.github.blemale.scaffeine.CacheLoaderAdapter.load(CacheLoaderAdapter.java:22)
    	at com.github.benmanes.caffeine.cache.CacheLoader.lambda$asyncLoad$0(CacheLoader.java:104)
    	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
    	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1692)
    	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
    	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
    	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
    	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
    	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)

**Comment by rikvdkleij** [comment]
Thanks for reporting!

Will fix that.

**Comment by rikvdkleij** [comment]
@harcokuppens which GHC/`base` version are you using?

**Comment by harcokuppens** [comment]
in our project we still use in the stack.yaml

  resolver: lts-11.22


$ stack exec -- ghc --version
The Glorious Glasgow Haskell Compilation System, version 8.2.2

**Comment by rikvdkleij** [comment]
@harcokuppens Thanks! Could reproduce and fix this issue.

**Comment by harcokuppens** [comment]
Great, thanx for the fast, if I find more issues I will report them.

Best regards,
Harco Kuppens

**Comment by rikvdkleij** [comment]
Should be fixed in beta79.

**Comment by rikvdkleij** [comment]
Please reopen if still an issue.
