### ISSUE TITLE
There is Exception in plugin IntelliJ-Haskell (1.0.0-beta75)

### ISSUE THREAD

**Issue by Gaia0514** [rikvdkleij/intellij-haskell#606]
**stacktrace.txt**
1/3
`java.lang.NoSuchMethodError: 'com.intellij.lang.annotation.AnnotationBuilder com.intellij.lang.annotation.AnnotationHolder.newSilentAnnotation(com.intellij.lang.annotation.HighlightSeverity)'
	at intellij.haskell.highlighter.HighlightingAnnotator$.infoAnnotation(HaskellHighlightingAnnotator.scala:29)
	at intellij.haskell.highlighter.HaskellHighlightingAnnotator.annotate(HaskellHighlightingAnnotator.scala:19)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.runAnnotators(DefaultHighlightVisitor.java:126)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.visit(DefaultHighlightVisitor.java:108)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.runVisitors(GeneralHighlightingPass.java:351)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$collectHighlights$5(GeneralHighlightingPass.java:285)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:311)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$6(GeneralHighlightingPass.java:314)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.analyze(DefaultHighlightVisitor.java:93)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:314)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectHighlights(GeneralHighlightingPass.java:282)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectInformationWithProgress(GeneralHighlightingPass.java:227)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:84)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:55)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$null$1(PassExecutorService.java:429)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:997)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:422)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:585)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:531)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:421)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:397)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:167)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:157)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:395)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:161)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)`

2/3
`java.lang.NoSuchMethodError: 'com.intellij.openapi.application.NonBlockingReadAction com.intellij.openapi.application.NonBlockingReadAction.wrapProgress(com.intellij.openapi.progress.ProgressIndicator)'
	at intellij.haskell.util.ApplicationUtil$.runReadAction(ApplicationUtil.scala:43)
	at intellij.haskell.external.component.StackProjectManager$$anon$2.$anonfun$run$27(StackProjectManager.scala:269)
	at scala.collection.StrictOptimizedIterableOps.map(StrictOptimizedIterableOps.scala:99)
	at scala.collection.StrictOptimizedIterableOps.map$(StrictOptimizedIterableOps.scala:86)
	at scala.collection.mutable.ArrayBuffer.map(ArrayBuffer.scala:40)
	at intellij.haskell.external.component.StackProjectManager$$anon$2.$anonfun$run$21(StackProjectManager.scala:269)
	at intellij.haskell.util.ScalaUtil$.$anonfun$runnable$1(ScalaUtil.scala:35)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:238)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)`

3/3
`java.lang.NoSuchMethodError: 'com.intellij.openapi.application.NonBlockingReadAction com.intellij.openapi.application.NonBlockingReadAction.wrapProgress(com.intellij.openapi.progress.ProgressIndicator)'
	at intellij.haskell.util.ApplicationUtil$.runReadAction(ApplicationUtil.scala:43)
	at intellij.haskell.cabal.CabalInfo.executables$lzycompute(CabalInfo.scala:77)
	at intellij.haskell.cabal.CabalInfo.executables(CabalInfo.scala:76)
	at intellij.haskell.module.HaskellModuleBuilder$.$anonfun$getDependencies$5(HaskellModuleBuilder.scala:207)
	at scala.Option.map(Option.scala:242)
	at intellij.haskell.module.HaskellModuleBuilder$.getDependencies(HaskellModuleBuilder.scala:207)
	at intellij.haskell.module.HaskellModuleBuilder$.$anonfun$addLibrarySources$4(HaskellModuleBuilder.scala:301)
	at scala.collection.Iterator$$anon$9.next(Iterator.scala:575)
	at scala.collection.immutable.List.prependedAll(List.scala:153)
	at scala.collection.immutable.List$.from(List.scala:651)
	at scala.collection.immutable.List$.from(List.scala:648)
	at scala.collection.IterableOps$WithFilter.map(Iterable.scala:885)
	at intellij.haskell.module.HaskellModuleBuilder$.$anonfun$addLibrarySources$1(HaskellModuleBuilder.scala:300)
	at intellij.haskell.module.HaskellModuleBuilder$.$anonfun$addLibrarySources$1$adapted(HaskellModuleBuilder.scala:286)
	at scala.Option.foreach(Option.scala:437)
	at intellij.haskell.module.HaskellModuleBuilder$.addLibrarySources(HaskellModuleBuilder.scala:286)
	at intellij.haskell.external.component.StackProjectManager$$anon$2.$anonfun$run$36(StackProjectManager.scala:308)
	at intellij.haskell.util.ScalaUtil$.$anonfun$runnable$1(ScalaUtil.scala:35)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:238)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)`

**Comment by rikvdkleij** [comment]
Looks like the combination of IntelliJ version and plugin version don't match. Please update IntelliJ and plugin to latest version.

**Comment by Gaia0514** [comment]
Oh!
Thank you so much.
I updated IntelliJ 2020.2.1.
