### ISSUE TITLE
Argument for @NotNull parameter 

### ISSUE THREAD

**Issue by nhenin** [rikvdkleij/intellij-haskell#653]
Intellij is freezing every 10s showing the following error : 

```
2021-04-29 16:09:50,829 [1792467]  ERROR - aemon.impl.PassExecutorService - IntelliJ IDEA 2021.1  Build #IC-211.6693.111
2021-04-29 16:09:50,829 [1792467]  ERROR - aemon.impl.PassExecutorService - JDK: 11.0.10; VM: Dynamic Code Evolution 64-Bit Server VM; Vendor: JetBrains s.r.o.
2021-04-29 16:09:50,829 [1792467]  ERROR - aemon.impl.PassExecutorService - OS: Mac OS X
2021-04-29 16:09:50,830 [1792468]  ERROR - aemon.impl.PassExecutorService - Plugin to blame: IntelliJ-Haskell version: 1.0.0-beta85
2021-04-29 16:09:50,830 [1792468]  ERROR - aemon.impl.PassExecutorService - Last Action: EditorUpWithSelection
2021-04-29 16:09:50,830 [1792468]  ERROR - aemon.impl.PassExecutorService - Argument for @NotNull parameter 'endElement' of com/intellij/codeInspection/ProblemDescriptorBase.<init> must not be null
java.lang.IllegalArgumentException: Argument for @NotNull parameter 'endElement' of com/intellij/codeInspection/ProblemDescriptorBase.<init> must not be null
	at com.intellij.codeInspection.ProblemDescriptorBase.$$$reportNull$$$0(ProblemDescriptorBase.java)
	at com.intellij.codeInspection.ProblemDescriptorBase.<init>(ProblemDescriptorBase.java)
	at intellij.haskell.inspection.HLintInspectionTool.$anonfun$checkFile$6(HLintInspectionTool.scala:96)
	at scala.Option.map(Option.scala:242)
	at intellij.haskell.inspection.HLintInspectionTool.$anonfun$checkFile$5(HLintInspectionTool.scala:74)
	at scala.collection.Iterator$$anon$10.nextCur(Iterator.scala:585)
	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:599)
	at scala.collection.immutable.List.prependedAll(List.scala:152)
	at scala.collection.immutable.List$.from(List.scala:651)
	at scala.collection.immutable.List$.from(List.scala:648)
	at scala.collection.IterableOps$WithFilter.flatMap(Iterable.scala:888)
	at intellij.haskell.inspection.HLintInspectionTool.checkFile(HLintInspectionTool.scala:71)
	at com.intellij.codeInspection.LocalInspectionTool$1.visitFile(LocalInspectionTool.java:145)
	at com.intellij.extapi.psi.PsiFileBase.accept(PsiFileBase.java:60)
	at com.intellij.codeInspection.InspectionEngine.acceptElements(InspectionEngine.java:65)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$visitRestElementsAndCleanup$7(LocalInspectionsPass.java:346)
	at com.intellij.util.AstLoadingFilter.lambda$toComputable$2(AstLoadingFilter.java:174)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:132)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:121)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:111)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$visitRestElementsAndCleanup$10(LocalInspectionsPass.java:346)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:136)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1096)
	at com.intellij.concurrency.ApplierCompleter.lambda$wrapInReadActionAndIndicator$1(ApplierCompleter.java:92)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:688)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:634)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:64)
	at com.intellij.concurrency.ApplierCompleter.wrapInReadActionAndIndicator(ApplierCompleter.java:104)
	at com.intellij.concurrency.ApplierCompleter.lambda$compute$0(ApplierCompleter.java:83)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:167)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:178)
	at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:83)
	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
2021-04-29 16:09:50,831 [1792469]  ERROR - aemon.impl.PassExecutorService - IntelliJ IDEA 2021.1  Build #IC-211.6693.111
2021-04-29 16:09:50,831 [1792469]  ERROR - aemon.impl.PassExecutorService - JDK: 11.0.10; VM: Dynamic Code Evolution 64-Bit Server VM; Vendor: JetBrains s.r.o.
```

**Comment by rikvdkleij** [comment]
Thanks for reporting! Could be an issue of 2021.1 because I didn’t test the plugin with that version yet.

**Comment by rikvdkleij** [comment]
Should be fixed in beta88, https://github.com/rikvdkleij/intellij-haskell/releases/tag/v1.0.0-beta88
