### ISSUE TITLE
Fatal error after create empty project

### ISSUE THREAD

**Issue by mariohuq** [rikvdkleij/intellij-haskell#655]
version (1.0.0-beta85)
stack version: Version 2.5.1, Git revision d6ab861544918185236cf826cb2028abb266d6d5 x86_64 hpack-0.33.0
```
java.lang.Exception: Unknown error while creating new Stack project by using Stack command for creating new project on file system
	at intellij.haskell.module.HaskellModuleBuilder.$anonfun$createStackProject$1(HaskellModuleBuilder.scala:152)
	at intellij.haskell.util.ScalaUtil$.$anonfun$runnable$1(ScalaUtil.scala:35)
	at com.intellij.util.RunnableCallable.call(RunnableCallable.java:20)
	at com.intellij.util.RunnableCallable.call(RunnableCallable.java:11)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.call(ApplicationImpl.java:265)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by VergeDX** [comment]
Same issues here, NixOS 21.05.
