### ISSUE TITLE
NullPointerException when adding Run Configuration

### ISSUE THREAD

**Issue by max333** [rikvdkleij/intellij-haskell#666]
When trying to add a Haskell Stack REPL (or Run or Test) configuration I get a NullPointerException.

I'm on Ubuntu 20.04, intellij.haskell (1.0.0-beta87) and Intellij 2021.2.1 (Build #IC-212.5080.55, built on August 23, 2021).  I reverted to Intellij 2021.2, but it did not help.  I'm not sure when this problem appeared since I don't add Run Configurations very often.

```
java.lang.NullPointerException
	at intellij.haskell.runconfig.console.HaskellConsoleConfigurationForm.<init>(HaskellConsoleConfigurationForm.java:15)
	at intellij.haskell.runconfig.console.HaskellConsoleConfiguration.getConfigurationEditor(HaskellConsoleConfiguration.scala:20)
	at intellij.haskell.runconfig.console.HaskellConsoleConfiguration.getConfigurationEditor(HaskellConsoleConfiguration.scala:14)
	at com.intellij.execution.impl.ConfigurationSettingsEditorWrapper.createWrapper(ConfigurationSettingsEditorWrapper.java:198)
	at com.intellij.execution.impl.SingleConfigurationConfigurable.<init>(SingleConfigurationConfigurable.java:81)
	at com.intellij.execution.impl.SingleConfigurationConfigurable.editSettings(SingleConfigurationConfigurable.java:118)
	at com.intellij.execution.impl.RunConfigurable.createNewConfiguration(RunConfigurable.kt:818)
	at com.intellij.execution.impl.RunConfigurable.createNewConfiguration(RunConfigurable.kt:853)
	at com.intellij.execution.impl.RunConfigurable$MyToolbarAddAction$showAddPopup$popup$1.consume(RunConfigurable.kt:895)
	at com.intellij.execution.impl.RunConfigurable$MyToolbarAddAction$showAddPopup$popup$1.consume(RunConfigurable.kt:866)
	at com.intellij.execution.impl.NewRunConfigurationPopup$5.onChosen(NewRunConfigurationPopup.java:254)
	at com.intellij.ui.popup.tree.TreePopupImpl.handleSelect(TreePopupImpl.java:357)
	at com.intellij.ui.popup.tree.TreePopupImpl$MyMouseListener.mousePressed(TreePopupImpl.java:307)
```

The stack trace is much longer, but the rest seems irrelevant.

**Comment by rikvdkleij** [comment]
Same as #662
