### ISSUE TITLE
New project error.

### ISSUE THREAD

**Issue by Zim-Inn** [rikvdkleij/intellij-haskell#696]
java.lang.Exception: Unknown error while creating new Stack project by using Stack command for creating new project on file system
	at intellij.haskell.module.HaskellModuleBuilder.$anonfun$createStackProject$1(HaskellModuleBuilder.scala:152)
	at intellij.haskell.util.ScalaUtil$.$anonfun$runnable$1(ScalaUtil.scala:35)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:246)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)

I met the error when I setup stack executable and then new project for Haskell module.
And my ghci button is still gray.
![image](https://user-images.githubusercontent.com/60260187/216335762-18e79606-76d0-4a73-a60f-ef76b3ccea11.png)

Both of my stack version and Idea version is latest/

**Comment by Zim-Inn** [comment]
![image](https://user-images.githubusercontent.com/60260187/216336570-d4e2f8dd-ff6b-4b29-ae67-d0acf2811169.png)
And when I import project from existing source, the Haskell option didn't occure.
