### ISSUE TITLE
Exception in plugin 1.0.0-beta88: "No display name specified in plugin descriptor XML file for configurable"

### ISSUE THREAD

**Issue by jiridanek** [rikvdkleij/intellij-haskell#700]
This appears to be quite common issue in intellij plugins, see for example

* https://github.com/intellij-dlanguage/intellij-dlanguage/issues/899#ref-commit-9ce6da3

```
com.intellij.diagnostic.PluginException: No display name specified in plugin descriptor XML file for configurable intellij.haskell.settings.HaskellConfigurable;
specify it using 'displayName' or 'key' attribute to avoid necessity to load the configurable class when Settings dialog is opened [Plugin: intellij.haskell]
	at com.intellij.openapi.options.ex.ConfigurableWrapper.getDisplayName(ConfigurableWrapper.java:156)
	at com.intellij.ide.util.gotoByName.GotoActionModel.lambda$new$0(GotoActionModel.java:86)
	at com.intellij.openapi.util.NotNullLazyValue$4.compute(NotNullLazyValue.java:119)
	at com.intellij.openapi.util.NotNullLazyValue$4.getValue(NotNullLazyValue.java:104)
	at com.intellij.ide.util.gotoByName.GotoActionModel.getConfigurablesNames(GotoActionModel.java:406)
	at com.intellij.ide.util.gotoByName.GotoActionItemProvider.processOptions(GotoActionItemProvider.java:148)
	at com.intellij.ide.util.gotoByName.GotoActionItemProvider.filterElements(GotoActionItemProvider.java:94)
	at com.intellij.ide.actions.searcheverywhere.ActionSearchEverywhereContributor.lambda$fetchWeightedElements$2(ActionSearchEverywhereContributor.java:144)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:610)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:685)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:641)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:609)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:78)
	at com.intellij.ide.actions.searcheverywhere.ActionSearchEverywhereContributor.fetchWeightedElements(ActionSearchEverywhereContributor.java:143)
	at com.intellij.searchEverywhereMl.semantics.contributors.SemanticActionSearchEverywhereContributor.defaultFetchElements(SemanticActionSearchEverywhereContributor.kt:181)
	at com.intellij.searchEverywhereMl.semantics.contributors.SemanticActionSearchEverywhereContributor$fetchElementsConcurrently$1$2.invoke(SemanticActionSearchEverywhereContributor.kt:137)
	at com.intellij.searchEverywhereMl.semantics.contributors.SemanticActionSearchEverywhereContributor$fetchElementsConcurrently$1$2.invoke(SemanticActionSearchEverywhereContributor.kt:136)
	at com.intellij.openapi.progress.CoroutinesKt.jobToIndicator$lambda$1(coroutines.kt:454)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:73)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:192)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:610)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:685)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:641)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:609)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:78)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:179)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:73)
	at com.intellij.openapi.progress.CoroutinesKt.jobToIndicator(coroutines.kt:442)
	at com.intellij.openapi.progress.CoroutinesKt.contextToIndicator(coroutines.kt:414)
	at com.intellij.openapi.progress.CoroutinesKt.coroutineToIndicator(coroutines.kt:351)
	at com.intellij.searchEverywhereMl.semantics.contributors.SemanticActionSearchEverywhereContributor$fetchElementsConcurrently$1.invokeSuspend(SemanticActionSearchEverywhereContributor.kt:136)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at com.intellij.openapi.progress.CoroutinesKt$runBlockingCancellable$1.invoke(coroutines.kt:133)
	at com.intellij.openapi.progress.CoroutinesKt$runBlockingCancellable$1.invoke(coroutines.kt:127)
	at com.intellij.openapi.progress.ContextKt.prepareIndicatorThreadContext$lambda$5(context.kt:110)
	at com.intellij.openapi.progress.impl.CoreProgressManager.silenceGlobalIndicator(CoreProgressManager.java:972)
	at com.intellij.openapi.progress.ContextKt.prepareIndicatorThreadContext(context.kt:108)
	at com.intellij.openapi.progress.ContextKt.prepareThreadContext(context.kt:78)
	at com.intellij.openapi.progress.CoroutinesKt.runBlockingCancellable(coroutines.kt:127)
	at com.intellij.openapi.progress.CoroutinesKt.runBlockingCancellable(coroutines.kt:122)
	at com.intellij.searchEverywhereMl.semantics.contributors.SemanticActionSearchEverywhereContributor.fetchElementsConcurrently(SemanticActionSearchEverywhereContributor.kt:97)
	at com.intellij.searchEverywhereMl.semantics.contributors.SemanticActionSearchEverywhereContributor.fetchWeightedElements$lambda$2(SemanticActionSearchEverywhereContributor.kt:78)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:610)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:685)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:641)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:609)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:78)
	at com.intellij.searchEverywhereMl.semantics.contributors.SemanticActionSearchEverywhereContributor.fetchWeightedElements(SemanticActionSearchEverywhereContributor.kt:77)
	at com.intellij.ide.actions.searcheverywhere.MixedResultsSearcher$ContributorSearchTask.run(MixedResultsSearcher.java:184)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:218)
	at com.intellij.util.ConcurrencyUtil.lambda$underThreadNameRunnable$3(ConcurrencyUtil.java:206)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:263)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:840)
```

```
IntelliJ IDEA 2023.3 EAP (Ultimate Edition)
Build #IU-233.11555.11, built on November 1, 2023
Licensed to IntelliJ IDEA EAP user: Jiri Daněk
Expiration date: December 1, 2023
Runtime version: 17.0.9+7-b1087.3 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 6.5.7-300.fc39.x86_64
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 12
Registry:
  freeze.reporter.profiling=false
  debugger.new.tool.window.layout=true
  ide.experimental.ui=true
Non-Bundled Plugins:
  com.jetbrains.plugins.ini4idea (233.11555.11)
  org.antlr.intellij.plugin (1.22)
  org.intellij.plugins.hcl (233.11555.11)
  com.jetbrains.rust (233.18264.32)
  org.jetbrains.plugins.go-template (233.11555.11)
  com.intellij.ideolog (222.1.0.0)
  name.kropp.intellij.makefile (233.11555.11)
  ir.msdehghan.plugins.ansible (0.92)
  org.jetbrains.plugins.go (233.11555.11)
  AceJump (3.8.16)
  com.intellij.grazie.pro (0.3.261)
  com.intellij.nativeDebug (233.11555.11)
  intellij.haskell (1.0.0-beta88)
  com.intellij.plugin.adernov.powershell (2.3.0)
  com.intellij.ml.llm (233.11555.11)
  dev.blachut.svelte.lang (233.11555.11)
  org.asciidoctor.intellij.asciidoc (0.41.0)
  Pythonid (233.11555.11)
  com.intellij.bigdatatools.core (233.11555.11)
  com.intellij.bigdatatools.binary.files (233.11555.11)
  com.intellij.bigdatatools.rfs (233.11555.11)
  mobi.hsz.idea.gitignore (4.5.2)
  com.carbonblack.intellij.rpmspec (2.2.0)
Kotlin: 233-1.9.0-release-358-IJ11555.11
Current Desktop: KDE
```

**Comment by jiridanek** [comment]
https://github.com/rikvdkleij/intellij-haskell/blob/eb8f485b4570ee33afc871291b24d8d7bcf7d773/intellij-haskell/META-INF/plugin.xml#L623-L627

**Comment by ehonsey** [comment]
See #702

**Comment by jiridanek** [comment]
I don't see these exceptions by default as popup in non-EAP intellij builds, and I don't quite know how to check. I'm willing to take https://github.com/rikvdkleij/intellij-haskell/pull/702 on faith. Thanks! I'll report back if I ever see that popup again in next EAP.
