### ISSUE TITLE
[global-stack-repl] Invalid options

### ISSUE THREAD

**Issue by dvoraka** [rikvdkleij/intellij-haskell#92]
Hi, I am completely new to the plugin but it looks pretty good. When tried it I wasn't successful and don't know where could be a problem. I use Debian Jessie, Stack 1.3.0 and Idea 2016.3.1 Ultimate. In Idea event log it ends always with the same errors:

`[global-stack-repl] Stack repl will be started with command: /home/user/haskell/stack/stack repl --with-ghc intero --verbosity warn --fast --no-load --no-build --ghc-options -v1 --terminal --no-package-hiding`

```
Build of `haskell-docs`, `hlint` and `apply-refact` is finished
```
```
[global-stack-repl] Invalid option `--fast'
					Usage: stack repl [TARGET/FILE] [--ghci-options OPTION] [--with-ghc GHC]
					[--[no-]load] [--package ARG] [--main-is TARGET]
					[--load-local-deps] [--[no-]package-hiding] [--trace]
					[--profile] [--[no-]test] [--[no-]bench] [--help]
					Run ghci in the context of package(s) (experimental) (alias for 'ghci')
```
When I try the command from a command line the error is the same. Thanks for any tips.

I read info here about building **intero**, so I tried in project directory too:
```
$ stack build intero
Fetching package index ...remote: Counting objects: 824691, done.
remote: Compressing objects: 100% (108/108), done.
remote: Total 824691 (delta 30), reused 0 (delta 0), pack-reused 824579
Receiving objects: 100% (824691/824691), 205.95 MiB | 505.00 KiB/s, done.
Resolving deltas: 100% (348722/348722), done.
From https://github.com/commercialhaskell/all-cabal-hashes
 * [new branch]      display    -> origin/display
 * [new branch]      hackage    -> origin/hackage
 * [new tag]         current-hackage -> current-hackage
Fetched package index.    
Populated index cache. 
$
```

**Comment by zjhmale** [comment]
@dvoraka stack 1.3.0 is quite new and the `--fast` for `stack repl` command is already removed in the next release of this plugin.

@rikvdkleij Maybe we should release `1.0.0.beta4` ASAP

**Comment by dvoraka** [comment]
Thanks, I can try Stack 1.2.* in meantime.

**Comment by dvoraka** [comment]
Cool, it works with Stack 1.2.0. Really good plugin!

**Comment by rikvdkleij** [comment]
@zjhmale yes, I want to release new beta this week. I want to test some more and take a look to PR #73.

**Comment by chrissound** [comment]
I've run into this as well. @dvoraka what was involved in downgrading to stack 1.2 - if you don't mind! 

Cheers

**Comment by dvoraka** [comment]
@chrissound Do you want steps to downgrade?

**Comment by chrissound** [comment]
@dvoraka Yes please!

**Comment by rikvdkleij** [comment]
@dvoraka I will release beta 4 today...

**Comment by dvoraka** [comment]
No problem. What OS do you use? I downloaded Stack 1.2.0 here:
https://github.com/commercialhaskell/stack/releases

I have a link to the Stack directory so then changed it to 1.2.0.

It is possible that you will need some development versions of libraries for your system. I work on some testing project (https://github.com/dvoraka/hstest) so you can try some steps before you start Idea. It is easier to find problems.

**Comment by rikvdkleij** [comment]
It's released. It should be (soon) visible in Plugins.

**Comment by chrissound** [comment]
I've just updated to the new release and I'm getting this, just about to try updating intellij.
```
Cannot run program "/usr/bin" (in directory "/home/archie/projects/hbook/mybeT"): error=13, Permission denied
com.intellij.execution.process.ProcessNotCreatedException: Cannot run program "/usr/bin" (in directory "/home/archie/projects/hbook/mybeT"): error=13, Permission denied
	at com.intellij.execution.configurations.GeneralCommandLine.createProcess(GeneralCommandLine.java:369)
	at com.intellij.execution.process.OSProcessHandler.<init>(OSProcessHandler.java:45)
	at com.intellij.execution.process.CapturingProcessHandler.<init>(CapturingProcessHandler.java:38)
	at intellij.haskell.external.commandLine.CommandLine$$anon$1.<init>(CommandLine.scala:42)
	at intellij.haskell.external.commandLine.CommandLine$.run(CommandLine.scala:42)
	at intellij.haskell.external.commandLine.CommandLine$.runProgram(CommandLine.scala:37)
	at intellij.haskell.external.commandLine.StackCommandLine$.$anonfun$runCommand$1(StackCommandLine.scala:41)
	at scala.Option.flatMap(Option.scala:171)
	at intellij.haskell.external.commandLine.StackCommandLine$.runCommand(StackCommandLine.scala:33)
	at intellij.haskell.external.commandLine.StackCommandLine$.executeBuild(StackCommandLine.scala:47)
	at intellij.haskell.external.repl.StackReplProcess.start(StackReplProcess.scala:130)
	at intellij.haskell.external.component.StackProjectStartupManager$$anon$1.run(StackProjectStartupManager.scala:44)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:710)
	at com.intellij.openapi.progress.impl.CoreProgressManager$3.run(CoreProgressManager.java:179)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:568)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:519)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:164)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl$1.run(ProgressManagerImpl.java:128)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:309)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: Cannot run program "/usr/bin" (in directory "/home/archie/projects/hbook/mybeT"): error=13, Permission denied
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at com.intellij.execution.configurations.GeneralCommandLine.startProcess(GeneralCommandLine.java:379)
	at com.intellij.execution.configurations.GeneralCommandLine.createProcess(GeneralCommandLine.java:365)
	... 24 more
Caused by: java.io.IOException: error=13, Permission denied
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 26 more

```

**Comment by rikvdkleij** [comment]
Yeah, that is because of breaking change mentioned in Readme. It surprises me that you did not get error about the path to Stack binary is not set. 

You have to create Haskell Tool Stack SDK which contains path to Stack binary instead of path to folder which contains Stack binary.

**Comment by chrissound** [comment]
Oh right, yes as I've previously installed the plugin and set the path then. 

Tried update the path, but that didn't work for some reason, so had to 'remove' the  and then 'add' it again (within 'Project structure > SDKs').

It's running through some stack build commands now. Fingers crossed! Many thanks

**Comment by chrissound** [comment]
It seems to be working successfully now, well done!

Just curious, does this plugin support source code navigation into third party packages (dependencies installed from cabal / stack)?

**Comment by dvoraka** [comment]
Same here, works fine. Good job!

But I found a new trouble and I am not sure if it necessary. When I try command:
```
stack hoogle --rebuild
Hoogle isn't installed or is too old. Automatically installing (use --no-setup to disable) ...
Minimum version is hoogle-5.0. Found acceptable hoogle-5.0.6 in your index, installing it.

Error: While constructing the build plan, the following exceptions were encountered:

In the dependencies for hoogle-5.0.6:
    haskell-src-exts-1.17.1 must match >=1.18 && <1.20 (latest applicable is 1.19.1)
```

Is it a problem? Or can I solve it somehow?

**Comment by rikvdkleij** [comment]
Yes, in different ways. By going to Declaration or by navigation in Navigate menu, see also features in Readme. If everything went okay, the sources of dependencies are downloaded.

**Comment by rikvdkleij** [comment]
Hoogle 5.0.4 has to be automatically installed by plugin when opening project. Is it still busy building? Or otherwise restart project.

**Comment by dvoraka** [comment]
I reimport the project and everything is fine. The trouble was while rebuilding the database it found my testing project and it is probably a bit broken from Hoogle's perspective. So no problem with rebuilding but in rebuilding and with my project :)
